
import subprocess

process_purpose = {
    "init": "Main system init process. Boots all services and daemons.",
     "android.hardware.sensors-service.multihal":
        "Android Sensors HAL service (multi-HAL). Manages access to device sensors like accelerometer, gyroscope, magnetometer, and proximity sensors, providing sensor data to apps and system components efficiently.",
    "[kthreadd]": "Kernel thread manager. Creates and manages kernel threads.",
    "[pool_workqueue_release]": "Releases worker threads from the kernel workqueue.",
    "android.hardware.usb-aidl-service.mediatekv1.0":
        "Android USB HAL service (MediaTek). Manages USB hardware and communication, including OTG, charging detection, and data transfer, providing USB access to apps and system components via AIDL.",
        "android.hardware.usb-aidl-service.mediatekv1.0":
        "Android USB AIDL HAL service (MediaTek). Manages general USB interfaces and communication between the OS and USB hardware using AIDL.",
    "android.hardware.usb.gadget-aidl-service.mediatekv1.0":
        "Android USB Gadget HAL service (MediaTek). Handles USB gadget functionality, enabling the device to act as a USB peripheral (e.g., MTP, ADB, RNDIS), providing interfaces to the system and apps via AIDL.",
    "android.hardware.usb.gadget-service":
        "Legacy Android USB Gadget HAL service. Provides USB peripheral functionality without using AIDL, manages USB configuration and data transfer.",  
    "android.hardware.usb.service":
        "Core Android USB service. Manages USB host and device modes, communicates with HALs to control USB ports, and handles USB state notifications for apps and system.",
    "[kworker/R-rcu_g]": "RCU grace-period handling worker.",
    'vtservice_aidl': "Video Telephony (VT) AIDL service. Manages video call setup, streaming, and control between OS, apps, and modem.",
    'vtservice': "Video Telephony core service. Handles video encoding/decoding, session management, and signaling for video calls.",
    'vt_daemon': "Background daemon for Video Telephony. Supports persistent VT operations and inter-process communication.",
    'vt_hal': "Hardware Abstraction Layer for Video Telephony. Interfaces with device camera, codec, and modem hardware for VT.",
    'vt_proxy': "Proxy service for VT requests. Routes calls between the main VT service and other apps or system components.",
    'vt_network_service': "Manages network signaling and quality for video calls, including bandwidth and session stability.",
    'vt_camera_service': "Controls camera access for VT, including switching between front/back cameras during video calls.",
    'vt_codec_service': "Handles encoding and decoding of video streams for VT sessions.",
    'vt_ui_service': "Manages user interface components for video calling, like preview, in-call video display, and notifications.",
    "[kworker/R-slub_]": "SLUB memory allocator background tasks.",
    "[kworker/R-netns]": "Network namespace related kernel work.",
    "[kworker/R-mm_pe]": "Memory management: page events handler.",
    "[rcu_tasks_kthread]": "RCU tasks handling kernel thread.",
    "[rcu_tasks_trace_kthread]": "RCU tracing tasks thread.",
    "[ksoftirqd/0]": "Soft IRQ handler for CPU0.",
    "[rcu_preempt]": "RCU preemption handling.",
    "[rcub/0]": "RCU bottom-half handler for CPU0.",
    "[rcu_exp_gp_kthread_worker]": "Expedited RCU grace-period worker.",
    "[rcu_exp_par_gp_kthread_worker]": "Parallel expedited RCU worker.",
    "[migration/0]": "Moves tasks between CPU cores (CPU0).",
    "[idle_inject/0]": "Injects idle cycles for power management.",
    "[cpuhp/0]": "CPU hotplug manager for CPU0.",
    "[cpuhp/1]": "CPU hotplug manager for CPU1.",
    "[idle_inject/1]": "Idle cycle injector for CPU1.",
    "[migration/1]": "Task migration thread for CPU1.",
    "[ksoftirqd/1]": "Soft IRQ handler for CPU1.",
    "[cpuhp/2]": "CPU hotplug manager for CPU2.",
    "[idle_inject/2]": "Idle cycle injector for CPU2.",
    "[migration/2]": "Task migration thread for CPU2.",
    "[ksoftirqd/2]": "Soft IRQ handler for CPU2.",
    "[cpuhp/3]": "CPU hotplug manager for CPU3.",
    "[idle_inject/3]": "Idle cycle injector for CPU3.",
     "[mtk_wmtd_worker]": "Worker thread for the MediaTek WMT daemon, handling background wireless module operations such as Wi-Fi/Bluetooth/GPS communication tasks",
    "[mtk_wmtd_worker/0]": "MediaTek WMT worker thread executing wireless subsystem tasks on CPU 0",
    "[mtk_wmtd_worker/1]": "MediaTek WMT worker thread executing wireless subsystem tasks on CPU 1",
    "[mtk_wmtd_worker/2]": "MediaTek WMT worker thread executing wireless subsystem tasks on CPU 2",
    "[mtk_wmtd_worker/3]": "MediaTek WMT worker thread executing wireless subsystem tasks on CPU 3",
    "[mtk_wmtd_worker-high]": "High-priority WMT worker thread used for critical wireless hardware operations",
    "[mtk_wmtd_worker-low]": "Low-priority WMT worker handling background wireless maintenance tasks",
     "[sugov:0]": "CPU frequency scaling thread for CPU core 0, part of the schedutil governor managing performance and power",
    "[sugov:1]": "CPU frequency scaling thread for CPU core 1 controlled by the schedutil governor",
    "[sugov:2]": "CPU frequency scaling thread for CPU core 2 managing dynamic frequency adjustments",
    "[sugov:3]": "CPU frequency scaling thread for CPU core 3 handling power vs performance balancing",
    "[sugov:4]": "Schedutil governor CPU frequency manager for core 4",
    "[sugov:5]": "Schedutil governor CPU frequency manager for core 5",
    "[sugov:6]": "Schedutil governor CPU frequency manager for core 6",
    "[sugov:7]": "Schedutil governor CPU frequency manager for core 7",
    "[migration/3]": "Task migration thread for CPU3.",
    "[ksoftirqd/3]": "Soft IRQ handler for CPU3.",
    "[cpuhp/4]": "CPU hotplug manager for CPU4.",
    'android.hardware.lights-service.mediatek': "Manages device LEDs and backlight, controlling brightness, notification lights, and power-saving modes.",
    "[idle_inject/4]": "Idle cycle injector for CPU4.",
    "[migration/4]": "Task migration thread for CPU4.",
    "[ksoftirqd/4]": "Soft IRQ handler for CPU4.",
    "[cpuhp/5]": "CPU hotplug manager for CPU5.",
        'android.hardware.memtrack-service.mediatek': "Tracks memory usage of processes and graphics buffers to report to system services for monitoring and debugging.",
    "[idle_inject/5]": "Idle cycle injector for CPU5.",
    "[migration/5]": "Task migration thread for CPU5.",
    "[ksoftirqd/5]": "Soft IRQ handler for CPU5.",
    "mtk_lbs_service":
        "MediaTek Location Based Service (LBS) daemon. Handles GPS, AGPS, Wi-Fi positioning, and location assistance functions for navigation and location-aware apps.",
    "mrmd_isee":
        "MediaTek iSee secure resource manager daemon. Handles secure memory, secure tasks, and communication between TEE (Trusted Execution Environment) and Android system for operations like DRM, biometrics, and protected data handling.",
         "vendor.mediatek.hardware.mtkpower_applist-service.mediatek":
        "MediaTek Power AppList service. Manages the list of apps for power optimization, applying CPU/GPU throttling, battery-saving rules, thermal policies, and performance boosts based on foreground/background app states.",
         "android.hardware.thermal@2.0-service-mediatek":
        "Older version of the MediaTek Thermal HAL. Monitors sensors and applies throttling actions.",
    "vendor.mediatek.hardware.thermal-service":
        "Vendor thermal manager. Reads thermal zones and provides data to system thermal services.",
    "thermal_manager":
        "Core thermal management daemon. Applies CPU/GPU throttling, monitors temp zones, and coordinates with kernel thermal drivers.",
    "thermalservice":
        "System-level thermal service that communicates with apps and UI for throttling alerts.",
    "mtk_thermal_monitor":
        "Monitors MTK-specific thermal sensors and reports data to Thermal HAL.",
    "mtk_thermald":
        "MediaTek thermal daemon that enforces throttling rules based on temperature.",
    "mtk_therm_mgr":
        "Thermal policy manager. Decides throttling levels for CPU, GPU, modem, and battery.",
    "thermal-engine":
        "General thermal engine that reads temp values and enforces device cooling policies.",
    "mtk_gpufreqd":
        "Manages GPU frequency throttling based on thermal limits.",
    "mtk_cpufreqd":
        "Controls CPU frequency scaling under thermal stress.",
    "thermal_relayd":
        "Relays sensor temperature data to other system services like thermal HAL and powerHAL.",
    "cooling_dev_daemon":
        "Controls cooling devices: software cooling, fan (if any), charging slowdown.",
    "charging_thermal_service":
        "Slows down charging to maintain battery temperature safety.",
    "mtk_battery_thermal":
        "Monitors battery temperature and cuts power or slows charging when needed.",
    "android.hardware.thermal-service.mediatek":
        "MediaTek Thermal HAL service. Monitors CPU, GPU, battery, and board temperature and applies thermal throttling to prevent overheating. Works with PowerHAL and Kernel thermal drivers.",
    "mifaced":
        "Mi Face Authentication Daemon. Handles face recognition processing, face data management, sensor communication, and secure authentication for unlocking and app login.",
    "[cpuhp/6]": "CPU hotplug manager for CPU6.",
    "[idle_inject/6]": "Idle cycle injector for CPU6.",
     "vendor.mediatek.hardware.mtkpower@1.0-service":
        "Legacy MTK PowerHAL version. Handles CPU/GPU boosting and power hints for apps.",
    "vendor.mediatek.hardware.mtkpower@2.0-service":
        "Updated PowerHAL providing refined hints for gaming, scrolling, UI smoothness, and battery modes.",
    "vendor.mediatek.hardware.mtkpower_applist-service.mediatek":
        "AppList service for PowerHAL. Decides which app gets boost or battery restrictions.",
    "mtkpowerd":
        "Core MTK power daemon that enforces power policies, governor changes, and boost levels.",
    "mtk_power_manager":
        "Manages CPU cores online/offline, DVFS tables, and performance modes.",
    "mtk_performance_service":
        "General performance service controlling CPU/GPU DVFS and scheduling boosts.",
    "mtkperf_native":
        "Native performance daemon handling low-level boost requests from gaming engines and heavy apps.",
    "mtk_performance_res":
        "Resource manager that allocates CPU time, GPU memory, and thermal budget for apps.",
    "perfctl":
        "Performance controller utility used by MTK PowerHAL to apply boosts.",
    "mtk_sched_service":
        "Controls scheduler interactions such as load balancing and task grouping for performance.",
    "sugov": 
        "Scheduler Utilization Governor threads that adjust CPU frequency based on live usage.",
    "power_native_daemon":
        "Low-level power control daemon interfacing directly with kernel governors.",
        "vendor.mediatek.hardware.mtkpower-service.mediatek":
        "MediaTek PowerHAL service. Controls CPU/GPU frequencies, boosts, app performance modes, touch boost, and power-saving policies. Communicates with ThermalHAL, Kernel governors, and MTK performance daemons to balance performance and battery life.",
    "[migration/6]": "Task migration thread for CPU6.",
     "vendor.mediatek.hardware.nvram-service":
        "MediaTek NVRAM HAL service. Manages reading and writing non-volatile data such as IMEI, Wi-Fi MAC, Bluetooth MAC, modem configuration, radio calibration, and device-specific hardware settings stored in NVRAM partitions.",
        "nvram_daemon":
        "General NVRAM management daemon. Handles secure read/write operations.",
    "vendor.mediatek.hardware.nvram@1.1-service":
        "Older version of MTK NVRAM HAL, still used on many devices for compatibility.",
    "em_daemon":
        "Engineer Mode daemon. Provides access to calibration data stored in NVRAM.",
    "md_db_daemon":
        "Modem database daemon. Loads modem radio configuration parameters from NVRAM into the modem.",
    "mdlog_daemon":
        "Modem logging daemon using NVRAM partitions for debug/config.",
    "wifimac_daemon":
        "Handles Wi-Fi MAC address stored in NVRAM and ensures correct provisioning.",
    "btmac_daemon":
        "Provides Bluetooth MAC address to BT HAL from NVRAM.",
    "sensor_calibration_service":
        "Loads camera, gyro, accelerometer, proximity sensor calibration data stored in NVRAM.",
    "ccci_mdinit":
        "Initializes modem using NVRAM radio configuration and calibration data.",
    "[ksoftirqd/6]": "Soft IRQ handler for CPU6.",
    "[cpuhp/7]": "CPU hotplug manager for CPU7.",
    "[idle_inject/7]": "Idle cycle injector for CPU7.",
    "[migration/7]": "Task migration thread for CPU7.",
    "[ksoftirqd/7]": "Soft IRQ handler for CPU7.",
    "vendor.mediatek.hardware.nwk_opt@1.0-service":
        "MediaTek Network Optimization HAL. Manages data traffic optimization, packet scheduling, radio power-saving policies, VoLTE/IMS network tuning, and improves network efficiency for LTE/5G/Wi-Fi.",
        "vendor.mediatek.hardware.netdagent@1.0-service":
        "Handles network policy, routing, tethering, and firewall controls for MTK devices.",
    "vendor.mediatek.hardware.connscript-service":
        "Connectivity script daemon for optimizing Wi-Fi/LTE coexistence and handovers.",
    "vendor.mediatek.hardware.wifi-service":
        "MediaTek Wi-Fi HAL, manages Wi-Fi driver, scanning, MAC provisioning, and power controls.",
    "vendor.mediatek.hardware.wlanservice":
        "Driver-level Wi-Fi service for MTK chipsets.",
    "mtk_netd":
        "Customized network daemon supporting MTK data routing, firewall, tethering, and DNS handling.",
    "netd":
        "Android Network Daemon. Manages DNS, firewall, VPN, routing, and tethering.",
    "mtk_data_conn_service":
        "Handles LTE/5G data connection setup, APN switching, and radio data states.",
    "mtk_imsd":
        "IMS daemon managing VoLTE/VoWiFi call signaling and SIP network optimization.",
    "mtkrild":
        "Radio Interface Layer daemon that communicates with modem for network management.",
"vendor.mediatek.hardware.mtkpower-service.mediatek": "Mediatek power management (CPU/GPU tuning, battery optimization).",
    "vendor.mediatek.hardware.mtkpower_applist-service.mediatek": "App-specific power profiles and performance tuning.",
    "vendor.mediatek.hardware.nvram-service": "NVRAM access (IMEI, WiFi/BT MAC, modem configs, calibration data).",
    "vendor.mediatek.hardware.nwk_opt@1.0-service": "Network optimization (signal tuning, VoLTE/IMS performance).",
    "vendor.microtrust.hardware.soter@1.0-service": "Hardware security environment (TEE, secure keys, secure payments).",
    "vendor.mediatek.hardware.lbs@2.0-service": "Location-based services (GPS, AGPS, WiFi/cell location).",
    "vendor.mediatek.hardware.thermal@2.0-service": "Thermal management (temperature sensors, CPU throttling, overheating control).",
    "vendor.mediatek.hardware.videocodec-service": "Hardware video encode/decode (H.264, H.265).",
    "vendor.mediatek.hardware.sensors@2.0-service": "Hardware sensors (gyro, accelerometer, proximity, light).",
    "vendor.mediatek.hardware.dcm@1.0-service": "Data connection manager (stability, dual SIM switching).",
    "vendor.mediatek.hardware.wifi-hostapd-service": "WiFi Hotspot / Access Point mode hardware handler.",
    "vendor.mediatek.hardware.wlan@1.0-service": "WiFi chip control (radio scanning, 2.4GHz/5GHz control).",
    "vendor.mediatek.hardware.bluetooth@1.0-service": "Bluetooth hardware interface (pairing, audio, BLE).",
    "vendor.mediatek.hardware.keymaster@4.0-service": "Hardware encryption keys (fingerprint, face unlock, keystore).",
    "vendor.mediatek.hardware.misc-daemon": "Misc hardware tasks (vibrator, LED, backlight, small hardware drivers).",
    "vendor.mediatek.hardware.mms@1.0-service": "Modem Management Service (4G/5G, SIM radio control).",
    "vendor.mediatek.hardware.pq@2.0-service": "Display picture quality engine (color, contrast, HDR).",
    "vendor.mediatek.hardware.mtkradioex@2.0-service": "Extended radio service (dual SIM, VoLTE, IMS, emergency).",
    "vendor.microtrust.hardware.thh-service": "Trusted hardware security environment (TEE + banking).",
    "[kworker/7:0-events]": "Kernel async event handler.",
    "[kworker/R-inet_]": "Internet network stack event worker.",
    "vendor.xiaomi.hardware.displayfeature@1.0-service": "Xiaomi display features control (DC dimming, color enhancement, HDR tuning, adaptive brightness).",
    "[kauditd]": "Kernel audit logging daemon.",
    "[khungtaskd]": "Detects hung tasks in kernel.",
    "[oom_reaper]": "Kills memory-overloaded tasks after OOM.",
    "[kworker/R-write]": "Disk writeback worker.",
    "[kcompactd0]": "Memory page compaction worker.",
    "[kworker/R-kbloc]": "Kernel block I/O operations.",
    "[kworker/R-edac-]": "Memory ECC error detector worker.",
    "[kworker/R-devfr]": "Device framework event handler.",
    "[watchdogd]": "Kernel watchdog timer monitor.",
    "[kswapd0]": "Swaps memory pages to maintain RAM.",
    "[erofs_worker/0]": "EROFS filesystem worker.",
    "[kworker/R-kthro]": "Thermal throttling worker.",
    "[dmabuf-deferred-free-worker]": "Frees unused DMA buffers.",
    "[kworker/R-nvme-]": "NVMe storage event worker.",
    "[kworker/R-uas]": "USB Attached SCSI worker.",
    "[kworker/R-dm_bu]": "Device mapper background worker.",
    "[kworker/R-mld]": "Multicast listener discovery handler.",
    "[kworker/R-ipv6_]": "IPv6 network handling worker.",
    "[kworker/R-kstrp]": "Kernel string processing worker.",
    "[hang_detect]": "Detects system hang events.",
    "[hang_detect1]": "Backup hang detection thread.",
    "[kworker/R-mt-wd]": "MediaTek watchdog worker.",
    "[wdtk-0]": "Watchdog core 0.",
    "[wdtk-1]": "Watchdog core 1.",
    "[wdtk-2]": "Watchdog core 2.",
    "[wdtk-3]": "Watchdog core 3.",
    "[wdtk-4]": "Watchdog core 4.",
    "[wdtk-5]": "Watchdog core 5.",
    "[wdtk-6]": "Watchdog core 6.",
    "[wdtk-7]": "Watchdog core 7.",
    "[irq/172-mt6358-irq]": "PMIC interrupt handler.",
    "[irq/233-amms_irq]": "Audio/monitor sensor IRQ handler.",
    "[teei_switch_thread]": "Trusted Execution Environment switch.",
    "[teei_bdrv_thread]": "TEE block driver thread.",
    "[teei_log_thread]": "TEE logging thread.",
    "[irq/235-11240000.mmc]": "MMC storage interrupt handler.",
    "[irq/236-11230000.mmc]": "MMC storage interrupt handler.",
    "[irq/46-11240000.mmc]": "MMC interrupt handler.",
    "[kworker/R-regul]": "Voltage regulator events.",
    "[kworker/R-usb20]": "USB2.0 event worker.",
    "[irq/244-musb-hdrc]": "USB OTG MUSB interrupt.",
    "[kworker/R-mmc_c]": "MMC card event worker.",
    "spi0": "SPI bus controller 0.",
    "spi1": "SPI bus controller 1.",
    "spi2": "SPI bus controller 2.",
    "spi3": "SPI bus controller 3.",
    "spi4": "SPI bus controller 4.",
    "spi5": "SPI bus controller 5.",
    "[tcpc_timer_type_c_port0]": "USB-C power controller timer.",
    "[irq/69-type_c_port0-IRQ]": "USB-C IRQ handler.",
    "[kworker/R-lbat_]": "Battery low event worker.",
    "[cpuhp-ppm]": "Power/performance CPU management.",
    "[kworker/R-mmdvf]": "DVFS voltage scaling worker.",
    "[dma_pool_fill_thread]": "DMA memory pool filler.",
    "[cmdq_irq_thread]": "Command queue IRQ worker.",
    "[attach_thread]": "Driver attach events.",
    "[mtk_bat_irq_thread]": "Battery IRQ thread.",
    "[fgauge]": "Fuel gauge battery monitor.",
    "[battery_manager_thread]": "Battery charging/discharging manager.",
    "[power_misc_thread]": "Misc power management worker.",
    "[charger_thread]": "Charger hardware control.",
    "[tcpc_event_type_c_port0]": "USB-C event handler.",
    "[hwrng]": "Hardware random number generator.",
    "[xm_dfs_task]": "Dynamic frequency scaling worker.",
    "[disp_feature:0]": "Display feature manager.",
    "[card0-crtc0]": "Display controller pipeline 0.",
    "[card0-crtc1]": "Display controller pipeline 1.",
    "[card0-crtc2]": "Display controller pipeline 2.",
    "[card0-crtc3]": "Display controller pipeline 3.",
    "[mtk_drm_disp_idlemgr-0]": "DRM idle manager.",
    "[dis_ki-0]": "Display idle keep interactive.",
    "[enable_vblank]": "Vertical blank interrupt toggle.",
    "[mtk_drm_cwb]": "Content write-back thread.",
    "[irq/34-esd_err_irq]": "Display ESD error IRQ.",
    "[err_flag_chk]": "Error flag checker.",
    "[err_flag_irq_enable]": "Error flag IRQ enricher.",
    "[mtk_drm_fake_vsync:0]": "Fake vsync generator.",
    "[ddp_trig]": "Display pipeline trigger.",
    "[ddp_trig_d]": "Display pipeline trigger D.",
    "[ddp_cmdq_trig]": "Display command queue trigger.",
    "[pf_release_thread]": "Physical frame release worker.",
    "[sf_pf_release_thread]": "Surface frame release worker.",
    "[signal_fence]": "Graphics buffer fence handler.",
    "[mode_switch]": "Display mode switching.",
    "[smi_info_dump_thread]": "SMI debug information dumper.",
    "[mtk_drm_bind]": "DRM driver bind/unbind worker.",
    "[kworker/R-pure_]": "Display pure pipeline worker.",
    "[kworker/R-aal_r]": "Adaptive ambient light worker.",
    "[aal_sof_0]": "Ambient light start-of-frame job.",
    "jbd2/mmcblk0p11-8": "EXT4 journal handler.",
    "[kworker/R-ext4-]": "EXT4 filesystem background worker.",
    "[kworker/R-kdmfl]": "Flash storage layer worker.",
    "[kworker/R-kveri]": "Kernel verification worker.",
    "ueventd": "Handles device hotplug uevents.",
    "prng_seeder": "Seeds kernel random generator.",
    "[kworker/R-tls-s]": "TLS crypto worker.",
    "[krfcommd]": "Bluetooth RFCOMM layer.",
    "[kworker/R-SSPM_]": "Sub-system power manager.",
    "[kworker/R-sspm_]": "Sub-system power management events.",
    "[btif_rxd]": "Bluetooth RX handler.",
    "[pt_notify_thread]": "Power throttling notification.",
    "[conn-md-thread]": "Modem connectivity thread.",
    "[dlpt_notify_thread]": "Dynamic low-power throttling.",
    "[qos_ipi_recv]": "QoS messaging worker.",
    "[kworker/R-ged_n]": "GPU event daemon (normal).",
    "[kworker/R-ged_k]": "GPU event daemon (kernel).",
    "[kworker/R-ged_f]": "GPU event daemon (fast).",
    "[kworker/R-free_]": "Freeing unused kernel objects.",
    "[kworker/R-kbase]": "Mali GPU driver worker.",
    "[kworker/R-silfp]": "Fingerprint sensor worker.",
    "[bp_notify_thread]": "Battery protection notifications.",
    "[kworker/R-ccmni]": "Cellular modem network interface worker.",
    "[ccci_fsm]": "Modem finite state machine.",
    "[ccci_poll]": "Modem polling thread.",
    "[ccci_rpc_k]": "Modem RPC handler.",
    "[ccci_udc]": "USB modem controller.",
    "[ccci_ipc_3]": "Modem IPC channel 3.",
    "[ccci_ipc_6]": "Modem IPC channel 6.",
    "[ccci_ipc_7]": "Modem IPC channel 7.",
    "[ccci_ipc_8]": "Modem IPC channel 8.",
    "[ccci_sys]": "Modem system controller.",
    "[ccci_ctrl]": "Modem control thread.",
    "[krtatm]": "Real-time kernel timer.",
    "[kworker/R-bcct_]": "Battery current control worker.",
    "[kworker/R-SCP_W]": "System control processor worker (W).",
    "[kworker/R-SCP_L]": "SCP low-priority worker.",
    "[kworker/R-SCP_R]": "SCP regular tasks.",
    "[nanohub]": "Sensor hub main thread.",
    "[kworker/R-ipi_m]": "IPI messaging worker.",
    "[chre_kthread]": "Google CHRE sensor runtime.",
    "[scp_power_reset]": "SCP power reset handler.",
    "[kworker/R-accel]": "Accelerometer sensor worker.",
    "[kworker/R-gyro_]": "Gyroscope sensor worker.",
    "[kworker/R-mag_p]": "Magnetometer worker.",
    "[kworker/R-baro_]": "Barometer worker.",
    "[kworker/R-md_cl]": "Modem cleaner worker.",
    "[kworker/R-uethe]": "USB ethernet worker.",
    "logd": "System logging daemon.",
    "lmkd": "Low memory killer daemon.",
    "servicemanager": "Manages Android system services.",
    "hwservicemanager": "Hardware service registry.",
    "vndservicemanager": "Vendor service registry.",
    "[kworker/R-fts_w]": "Touchscreen worker.",
    "[psimon]": "Power scheduling monitor.",
    "[irq/29-fts_ts]": "Touchscreen IRQ handler.",
    "[id0_trusty_n/0]": "Trusty secure OS normal thread.",
    "[trusty_poll_task]": "Trusted OS polling job.",
    "volte_md_status": "VoLTE modem status monitor.",
    "vold": "Mount/Unmount storage daemon.",
    "android.hardware.boot-service.mtk": "MediaTek boot HAL service.",
    "[kworker/R-delay]": "Delayed workqueue worker.",
    "[kworker/R-accde]": "Accelerated display engine worker.",
    "[kworker/R-dismi]": "Display memory interface worker.",
    "jbd2/mmcblk0p17-8": "EXT4 journaling thread.",
    "ipi_cpu_dvfs_rtask": "CPU DVFS interrupt handler.",
    "[EEM_CTRL_L]": "Low-core voltage control.",
    "[EEM_CTRL_B]": "Big-core voltage control.",
    "[EEM_CTRL_CCI]": "CCI voltage control.",
    "[EEM_CTRL_GPU]": "GPU voltage control.",
    "Init_1_Stress": "System stress test task.",
    "[kworker/R-cpu_f]": "CPU frequency worker.",
    "[kworker/R-cpu_c]": "CPU cluster manager.",
    "[kworker/R-dram_]": "DRAM frequency worker.",
    "[kworker/R-vcore]": "Core voltage regulator.",
    "[kworker/R-usb_a]": "USB event worker.",
    "jbd2/mmcblk0p14-8": "EXT4 journaling for partition.",
    "jbd2/mmcblk0p18-8": "EXT4 journaling for partition.",
    "jbd2/mmcblk0p13-8": "EXT4 journaling for partition.",
    '[irq/46-11240000.mmc':"MMC/SD card controller ka interrupt handler (read/write, card detect, data transfer events).",
    "[spi0]": "SPI bus 0 driver thread handling SPI device communication",
    "[spi1]": "SPI bus 1 driver thread handling SPI device communication",
 "[spi2]": "SPI bus 2 driver thread handling communication with SPI devices",
    "[spi3]": "SPI bus 3 driver thread handling communication with SPI devices",
        "[kworker/1:3-events]": "Kernel worker thread on CPU 1, responsible for handling event-driven tasks and interrupt-related work",
    "[spi4]": "SPI bus 4 driver thread handling communication with SPI devices",
        "[kworker/4:0-events]": "Kernel worker on CPU 4 handling various system events from the event workqueue",
    "[spi5]": "SPI bus 5 driver thread handling communication with SPI devices",
      "[kworker/R-cmdq_]": "Kernel worker thread handling CMDQ (Command Queue) tasks for hardware acceleration and multimedia operations",
"[cmdq_buffer_usage]": "Monitors and manages the usage of CMDQ (Command Queue) buffers for hardware tasks",
"[irq/48-6-006a]": "Interrupt handler for device with IRQ 48, managing hardware events for that specific device",
"[fgauge": "Monitors battery level, voltage, and charge status via the fuel gauge hardware",
"[kworker/R-extco]": "Kernel worker thread handling external connectivity operations, such as managing external devices or communication interfaces",
 "[kworker/R-rcu_g]": "Kernel worker handling RCU (Read-Copy-Update) grace-period tasks",
     "[kworker/1:3-sock_diag_events]": "Kernel worker thread on CPU 1 that handles socket diagnostics events, monitoring and managing network socket activities",
     "[kworker/5:0-mm_percpu_wq]": "Kernel worker on CPU 5 handling memory management tasks on a per-CPU workqueue",
         "[kworker/2:3H-kverityd]": "Kernel worker thread on CPU 2 (high-priority) for handling dm-verity operations, ensuring integrity verification of the device's filesystem",
    "[kworker/R-slub_]": "Kernel worker for memory slab management",
        "[kworker/u16:1-cmdq_flushq]": "Kernel worker thread on CPU u16 handling command queue flush operations, ensuring queued hardware commands are executed and cleared properly",
        "[kworker/2:3H-fsverity_read_queue]": "Kernel worker thread on CPU 2 (high-priority) for processing fs-verity read operations, which verify file integrity during reads",
        "[kworker/4:3]": "Kernel worker thread on CPU 4, handling background tasks and deferred work in the kernel",
    "[kworker/R-netns]": "Kernel worker managing network namespace tasks",    "[kworker/1:3-mm_percpu_wq]": "Kernel worker handling memory management tasks per CPU (per-CPU workqueue)",
        "[kworker/0:2-events]": "Kernel worker handling general event processing tasks for CPU 0",
            "[kworker/1:0-events_freezable_power_]": "Kernel worker on CPU 1 handling events that can be frozen to save power",
                "[kworker/0:2H-fsverity_read_queue]": "Kernel worker thread on CPU 0 handling fs-verity read operations, which ensures integrity-verified reads from files protected by fs-verity",
                 "[kworker/0:0-events]": "Handles generic event work on CPU 0",
    "[kworker/0:0-mm_percpu_wq]": "Memory management work on CPU 0",
    "[kworker/0:0-sock_diag_events]": "Handles socket diagnostics work on CPU 0",
    "[kworker/0:1H-kblockd]": "Handles block I/O requests on CPU 0, high-priority",
    "[kworker/0:2H-fsverity_read_queue]": "Processes fs-verity read operations on CPU 0",
    "[kworker/0:2-events_freezable_power_]": "Event handling that can be frozen for power management on CPU 0",
    "[kworker/0:3H-kblockd]": "Block I/O requests on CPU 0, high-priority",
    "[kworker/1:0-events_freezable_power_]": "Event handling that can be frozen for power management on CPU 1",
    "[kworker/1:1H-kverityd]": "Handles kernel fs-verity operations on CPU 1",
    "[kworker/1:2-events_freezable_power_]": "Handles freezable events on CPU 1 for power management",
    "[kworker/1:3-mm_percpu_wq]": "Per-CPU memory management work on CPU 1",
    "[kworker/1:3-events]": "Handles general events on CPU 1",
    "[kworker/1:3-sock_diag_events]": "Handles socket diagnostic events on CPU 1",
    "[kworker/2:0-mm_percpu_wq]": "Per-CPU memory work on CPU 2",
    "[kworker/2:1-events]": "Handles events on CPU 2",
    "[kworker/2:2-events]": "Handles events on CPU 2",
    "[kworker/2:2H-kblockd]": "Block I/O requests on CPU 2, high-priority",
    "[kworker/2:3H-kverityd]": "Kernel fs-verity operations on CPU 2",
    "[kworker/2:3H-fsverity_read_queue]": "Processes fs-verity read operations on CPU 2",
    "[kworker/3:0H-kverityd]": "fs-verity operations on CPU 3",
    "[kworker/3:1H-kverityd]": "fs-verity operations on CPU 3",
    "[kworker/3:2H-kverityd]": "fs-verity operations on CPU 3",
    "[kworker/3:2-events]": "Handles events on CPU 3",
    "[kworker/3:3]": "General kworker tasks on CPU 3",
    "[kworker/3:3H-kverityd]": "fs-verity operations on CPU 3",
    "[kworker/4:0-events]": "Handles events on CPU 4",
    "[kworker/4:0-mm_percpu_wq]": "Memory management work on CPU 4",
    "[kworker/4:1H-kblockd]": "Block I/O requests on CPU 4, high-priority",
    "[kworker/4:2H-kverityd]": "fs-verity operations on CPU 4",
    "[kworker/5:0-mm_percpu_wq]": "Memory work on CPU 5",
    "[kworker/5:1H-kverityd]": "fs-verity operations on CPU 5",
    "[kworker/6:0H-kverityd]": "fs-verity operations on CPU 6",
    "[kworker/6:1H-kblockd]": "Block I/O requests on CPU 6, high-priority",
    "[kworker/0:0-events]": "Handles generic kernel events on CPU 0",
    "[kworker/0:0-mm_percpu_wq]": "Memory management tasks per CPU on CPU 0",
    "[kworker/0:0-sock_diag_events]": "Handles socket diagnostic events on CPU 0",
    "[kworker/0:1H-kblockd]": "Handles high-priority block I/O requests on CPU 0",
    "[kworker/0:2H-fsverity_read_queue]": "Processes fs-verity read operations on CPU 0",
    "[kworker/0:2-events_freezable_power_]": "Handles freezable events for power management on CPU 0",
    "[kworker/0:3H-kblockd]": "High-priority block I/O tasks on CPU 0",
    "[kworker/1:0-events_freezable_power_]": "Freezable events for power management on CPU 1",
    "[kworker/1:0-sock_diag_events]": "Socket diagnostic events on CPU 1",
    "[kworker/1:0-mm_percpu_wq]": "Memory management tasks on CPU 1",
    "[kworker/1:1H-kverityd]": "fs-verity verification tasks on CPU 1",
    "[kworker/1:2-events_freezable_power_]": "Freezable events for power management on CPU 1",
    "[kworker/1:3-mm_percpu_wq]": "Memory management tasks per CPU on CPU 1",
    "[kworker/1:3-events]": "General events handling on CPU 1",
    "[kworker/1:3-sock_diag_events]": "Socket diagnostic events on CPU 1",
    "[kworker/1:3H-fsverity_read_queue]": "fs-verity read operations on CPU 1",
    "[kworker/1:4-events_freezable_power_]": "Freezable events on CPU 1",
    "[kworker/2:0-mm_percpu_wq]": "Memory management tasks per CPU on CPU 2",
    "[kworker/2:0H-kblockd]": "High-priority block I/O on CPU 2",
    "[kworker/2:1-events]": "Handles events on CPU 2",
    "[kworker/2:2-events]": "Handles events on CPU 2",
    "[kworker/2:2H-kblockd]": "High-priority block I/O on CPU 2",
    "[kworker/2:3H-kverityd]": "fs-verity verification on CPU 2",
    "[kworker/2:3H-fsverity_read_queue]": "fs-verity read operations on CPU 2",
    "[kworker/3:0H-kverityd]": "fs-verity verification on CPU 3",
    "[kworker/3:1H-kverityd]": "fs-verity verification on CPU 3",
    "[kworker/3:2H-kverityd]": "fs-verity verification on CPU 3",
    "[kworker/3:2-events]": "Event handling on CPU 3",
    "[kworker/3:3]": "General kworker tasks on CPU 3",
    "[kworker/3:3H-kverityd]": "fs-verity verification on CPU 3",
    "[kworker/4:0-events]": "Handles events on CPU 4",
    "[kworker/4:0-mm_percpu_wq]": "Memory management tasks per CPU on CPU 4",
    "[kworker/4:1H-kblockd]": "High-priority block I/O on CPU 4",
    "[kworker/4:2H-kverityd]": "fs-verity verification on CPU 4",
    "[kworker/4:3]": "General kworker tasks on CPU 4",
    "[kworker/5:0-mm_percpu_wq]": "Memory management tasks on CPU 5",
    "[kworker/5:1H-kverityd]": "fs-verity verification on CPU 5",
    "[kworker/5:2H-kblockd]": "High-priority block I/O on CPU 5",
    "[kworker/6:0H-kverityd]": "fs-verity verification on CPU 6",
    "[kworker/6:1H-kblockd]": "High-priority block I/O on CPU 6",
    "[kworker/6:1-events]": "Event handling on CPU 6",
    "[kworker/7:2H-kblockd]": "Handles block I/O operations on CPU 7",
    "[kworker/6:2H-fsverity_read_queue]": "fs-verity read operations on CPU 6",
    "[kworker/6:3H-fsverity_read_queue]": "fs-verity read operations on CPU 6",
    "[kworker/6:4H-fsverity_read_queue]": "fs-verity read operations on CPU 6",
    "[kworker/6:6H-fsverity_read_queue]": "fs-verity read operations on CPU 6",
    "[kworker/6:8H-kblockd]": "High-priority block I/O on CPU 6",
    "[kworker/6:9H-kblockd]": "High-priority block I/O on CPU 6",
    "[kworker/7:0-events]": "Handles events on CPU 7",
    "[kworker/7:2H-fsverity_read_queue]": "Handles fs-verity read operations on CPU 7. Responsible for verifying integrity of file reads using fs-verity.",
    "[kworker/7:1H-kverityd]": "fs-verity verification on CPU 7",
    "[kworker/7:1H-fsverity_read_queue]": "Handles fs-verity read operations on CPU 7",
    "[kworker/7:2H-kverityd]": "fs-verity verification on CPU 7",
    "[kworker/7:3H]": "General kworker tasks on CPU 7",
    "[kworker/7:4H-kblockd]": "High-priority block I/O on CPU 7",
    "[kworker/5:3-events]": "Handles general event processing on CPU 5, such as deferred work, timers, and kernel events queued for execution.",
    "[kworker/u16:0-adb]": "Handles ADB tasks on CPU u16",
    "[kworker/u16:1-cmdq_flushq]": "Flush command queue on CPU u16",
    "[kworker/6:0H-fsverity_read_queue]": "Handles fs-verity read operations on CPU 6. It processes filesystem integrity verification tasks for secure reads.",
    "[kworker/u16:2-adb]": "Handles ADB tasks on CPU u16",
    "[kworker/u16:3-cmdq_pkt_destroy_wq]": "Command queue destroy work on CPU u16",
    "[kworker/u17:1-mali_jd]": "Mali GPU job handling on CPU u17",
    "[kworker/u17:2-mali_jd]": "Mali GPU job handling on CPU u17",
    "[kworker/u17:2-rx5_worker]": "Network RX worker thread on CPU u17",
    "[kworker/u17:3-composer_wq]": "Display composer work queue on CPU u17",
    "[kworker/u16:0-writeback]": "Handles writeback tasks on CPU 16. Responsible for flushing dirty pages from memory back to storage to maintain filesystem consistency.",
    "[kworker/6:1-events]": "Event handling on CPU 6",
    "[kworker/6:2H-fsverity_read_queue]": "Processes fs-verity read operations on CPU 6",
    "[kworker/6:3H-fsverity_read_queue]": "Processes fs-verity read operations on CPU 6",
    "[kworker/u16:0-flush-179:0]": "Handles specific block device flush operations on CPU 16, ensuring that pending I/O data is written from caches to the storage device.",
    "[kworker/6:4H-fsverity_read_queue]": "Processes fs-verity read operations on CPU 6",
    "[kworker/6:6H-fsverity_read_queue]": "Processes fs-verity read operations on CPU 6",
    "[kworker/6:8H-kblockd]": "Block I/O requests on CPU 6, high-priority",
    "[kworker/6:9H-kblockd]": "Block I/O requests on CPU 6, high-priority",
    "[kworker/7:0-events]": "Handles events on CPU 7",
    "[kworker/7:1H-kverityd]": "fs-verity operations on CPU 7",
    "[kworker/7:2H-kverityd]": "fs-verity operations on CPU 7",
    "[kworker/7:3H]": "General kworker tasks on CPU 7",
    "[kworker/7:4H-kblockd]": "Block I/O requests on CPU 7, high-priority",
    "[kworker/u16:0-adb]": "Handles ADB related background tasks on CPU u16",
    "[kworker/u16:1-cmdq_flushq]": "Command queue flush tasks on CPU u16",
    "[kworker/u16:2-adb]": "Handles ADB tasks on CPU u16",
    "[kworker/u17:1-mali_jd]": "Mali GPU job handling on CPU u17",
    "[kworker/u17:2-mali_jd]": "Mali GPU job handling on CPU u17",
    "[kworker/u17:2-rx5_worker]": "Network RX worker thread on CPU u17",
    "[kworker/u17:3-composer_wq]": "Display composer work queue on CPU u17",
    "[kworker/R-mm_pe]": "Kernel worker handling memory management and page events",
    "[kworker/7:0-events]": "Kernel worker handling background events for CPU 7",
    "[kworker/R-inet_]": "Kernel worker handling internet/network related background tasks",
    "[kworker/R-write]": "Kernel worker performing deferred write tasks",
    "[kworker/R-kbloc]": "Kernel worker handling block I/O tasks",
    "[kworker/R-edac-]": "Kernel worker handling EDAC (Error Detection and Correction) tasks",
    "[kworker/R-devfr]": "Kernel worker for device framework-related tasks",
    "[kworker/R-nvme-]": "Kernel worker managing NVMe storage tasks",
    "[kworker/R-uas]": "Kernel worker for USB Attached SCSI tasks",
    "[kworker/R-dm_bu]": "Kernel worker handling device-mapper background tasks",
    "[kworker/R-mld]": "Kernel worker handling multicast listener tasks",
    "[kworker/R-ipv6_]": "Kernel worker handling IPv6 network tasks",
    "[kworker/R-kstrp]": "Kernel worker handling kernel stack or tracing tasks",
    "[kworker/R-mt-wd]": "Kernel worker managing MediaTek watchdog tasks",
    "[kworker/R-lbat_]": "Kernel worker handling low battery events",
    "[kworker/R-mmdvf]": "Kernel worker managing MMDVF (media/device firmware) tasks",
    "[kworker/R-extco]": "Kernel worker handling external connectivity tasks",
    "[kworker/R-miev_]": "Kernel worker handling MIEV (Media/IO Event) tasks",
    "[kworker/R-cmdq_]": "Kernel worker handling CMDQ (Command Queue) tasks",
    "[kworker/R-pure_]": "Kernel worker performing background pure tasks",
    "[kworker/R-aal_r]": "Kernel worker for AAL (Adaptive Ambient Light) related tasks",
    "[kworker/R-ext4-]": "Kernel worker managing ext4 filesystem tasks",
    "[kworker/R-kdmfl]": "Kernel worker handling KDMFL (Kernel Data Management / File) tasks",
    "[kworker/R-kveri]": "Kernel worker managing Kernel Verification tasks",
    "[kworker/R-delay]": "Kernel worker handling delayed tasks",
    "[kworker/R-accde]": "Kernel worker managing accessory or sensor tasks",
    "[kworker/R-dismi]": "Kernel worker handling dismount or cleanup tasks",
    "[kworker/R-cpu_f]": "Kernel worker for CPU frequency adjustment tasks",
    "[kworker/R-cpu_c]": "Kernel worker for CPU core tasks",
    "[kworker/R-dram_]": "Kernel worker handling DRAM management tasks",
    "[kworker/R-vcore]": "Kernel worker for VCore voltage/power management",
    "[kworker/R-usb_a]": "Kernel worker handling USB accessory tasks",
    "[kworker/R-vdec_]": "Kernel worker managing video decoder tasks",
    "[kworker/R-lt_wq]": "Kernel worker for light-weight workqueue tasks",
    "[kworker/R-mt_us]": "Kernel worker for MediaTek specific microtasks",
    "[kworker/R-cfg80]": "Kernel worker handling configuration tasks",
    "[kworker/R-mt_fs]": "Kernel worker managing MediaTek filesystem tasks",
    "[kworker/R-compo]": "Kernel worker for component background tasks",
    "[kworker/R-fbt_c]": "Kernel worker handling frame buffer tasks",
    "[kworker/R-mt_mi]": "Kernel worker managing MediaTek MI tasks",
    "[kworker/R-fpt_c]": "Kernel worker handling fingerprint tasks",
    "[kworker/R-silfp]": "Kernel worker for SILFP (fingerprint sensor) tasks",
    "[kworker/R-ccmni]": "Kernel worker handling CCMNI (Cellular network interface) tasks",
    "[kworker/R-pool_]": "Kernel worker managing workqueue pool tasks",
    "[kworker/R-bcct_]": "Kernel worker for BCCT (Battery charge control tasks)",
    "[kworker/R-SCP_W]": "Kernel worker handling SCP W tasks",
    "[kworker/R-SCP_L]": "Kernel worker handling SCP L tasks",
    "[kworker/R-SCP_R]": "Kernel worker handling SCP R tasks",
    "[kworker/R-ipi_m]": "Kernel worker handling IPI messages",
    "[kworker/R-fts_w]": "Kernel worker managing FTS (fingerprint touch sensor) tasks",
    "[kworker/R-ged_n]": "Kernel worker for GED normal tasks",
    "[kworker/R-ged_k]": "Kernel worker for GED kernel tasks",
    "[kworker/R-ged_f]": "Kernel worker for GED foreground tasks",
    "[kworker/R-free_]": "Kernel worker managing memory free tasks",
    "[kworker/R-kbase]": "Kernel worker handling KBASE GPU driver tasks",
    "[kworker/R-md_tx]": "Kernel worker handling modem TX tasks",
    "[kworker/R-md_rx]": "Kernel worker handling modem RX tasks",
    "[kworker/R-fm_ti]": "Kernel worker handling FM transmit interrupt tasks",
    "[kworker/R-fm_ei]": "Kernel worker handling FM event interrupt tasks",
    "[kworker/u17:2-md_tx0_worker]": "Kernel worker handling modem TX0 tasks (user workqueue)",
    "[kworker/u17:1-md_tx0_worker]": "Kernel worker handling modem TX0 tasks (user workqueue)",
    "[kworker/u16:2-events_unbound]": "Kernel worker handling unbound event tasks",
    "[kworker/u16:4-events_unbound]": "Kernel worker handling unbound event tasks",
    "[kworker/u16:1-adb]": "Kernel worker handling ADB background tasks",
    "[kworker/u16:0-cmdq_pkt_destroy_wq]": "Kernel worker handling CMDQ packet destroy tasks",
    "[kworker/0:0-events]": "Kernel worker handling events on CPU 0",
    "[kworker/0:0H-fsverity_read_queue]": "Kernel worker handling fsverity read tasks on CPU 0",
    "[kworker/0:1-events_power_efficient]": "Kernel worker handling power-efficient events on CPU 0",
    "[kworker/0:2-mm_percpu_wq]": "Kernel worker handling memory management workqueue on CPU 0",
    "[kworker/0:2H-kblockd]": "Kernel worker handling block device tasks on CPU 0",
    "[kworker/1:0-events]": "Kernel worker handling events on CPU 1",
    "[kworker/1:1-mm_percpu_wq]": "Kernel worker handling memory management workqueue on CPU 1",
    "[kworker/1:4H-kverityd]": "Kernel worker handling verity tasks on CPU 1",
    "[kworker/1:5H-kblockd]": "Kernel worker handling block device tasks on CPU 1",
    "[kworker/2:0H-kverityd]": "Kernel worker handling verity tasks on CPU 2",
    "[kworker/2:1-events_freezable_power_]": "Kernel worker handling freezable power events on CPU 2",
    "[kworker/2:1H-kverityd]": "Kernel worker handling verity tasks on CPU 2",
    "[kworker/2:2-events_freezable_power_]": "Kernel worker handling freezable power events on CPU 2",
    "[kworker/2:2H-kverityd]": "Kernel worker handling verity tasks on CPU 2",
    "[kworker/2:3-events_freezable_power_]": "Kernel worker handling freezable power events on CPU 2",
    "[kworker/2:4H-kblockd]": "Kernel worker handling block device tasks on CPU 2",
    "[kworker/3:0H-kverityd]": "Kernel worker handling verity tasks on CPU 3",
    "[kworker/3:1H-kverityd]": "Kernel worker handling verity tasks on CPU 3",
    "[kworker/3:2-events]": "Kernel worker handling events on CPU 3",
    "[kworker/3:4H-kverityd]": "Kernel worker handling verity tasks on CPU 3",
    "[kworker/3:6-sock_diag_events]": "Kernel worker handling socket diagnostic events on CPU 3",
    "[kworker/4:0H-kblockd]": "Kernel worker handling block device tasks on CPU 4",
    "[kworker/4:1-events]": "Kernel worker handling events on CPU 4",
    "[kworker/4:2H-kverityd]": "Kernel worker handling verity tasks on CPU 4",
    "[kworker/4:3-events]": "Kernel worker handling events on CPU 4",
    "[kworker/5:0-events]": "Kernel worker handling events on CPU 5",
    "[kworker/5:1]": "Kernel worker background task on CPU 5",
    "[kworker/5:2H-kblockd]": "Kernel worker handling block device tasks on CPU 5",
    "[kworker/5:3H-fsverity_read_queue]": "Kernel worker handling fsverity read queue tasks on CPU 5",
    "[kworker/5:4-events]": "Kernel worker handling events on CPU 5",
    "[kworker/5:5H-fsverity_read_queue]": "Kernel worker handling fsverity read queue tasks on CPU 5",
    "[kworker/5:6H-fsverity_read_queue]": "Kernel worker handling fsverity read queue tasks on CPU 5",
    "[kworker/6:0H-kverityd]": "Kernel worker handling verity tasks on CPU 6",
    "[kworker/6:1-events]": "Kernel worker handling events on CPU 6",
    "[kworker/6:5H-kverityd]": "Kernel worker handling verity tasks on CPU 6",
    "[kworker/7:0H-kverityd]": "Kernel worker handling verity tasks on CPU 7",
    "[kworker/7:2-mm_percpu_wq]": "Kernel worker handling memory management workqueue on CPU 7",
    "[kworker/7:5H-kblockd]": "Kernel worker handling block device tasks on CPU 7",
 "[jbd2/mmcblk0p11-8]": "Journaling thread for ext4 filesystem on partition mmcblk0p11, handles write-ahead logging",
    "[jbd2/mmcblk0p11-1]": "Journaling thread for ext4 filesystem on partition mmcblk0p11, handles write-ahead logging",
    "[jbd2/mmcblk0p12-8]": "Journaling thread for ext4 filesystem on partition mmcblk0p12, handles write-ahead logging",
    "[jbd2/mmcblk0p12-1]": "Journaling thread for ext4 filesystem on partition mmcblk0p12, handles write-ahead logging",
    "[jbd2/mmcblk0p10-8]": "Journaling thread for ext4 filesystem on partition mmcblk0p10, handles write-ahead logging",
    "[jbd2/mmcblk0p10-1]": "Journaling thread for ext4 filesystem on partition mmcblk0p10, handles write-ahead logging",
"[id0_trusty_n/0]": "Trusty TEE (Trusted Execution Environment) normal world thread for secure operations",
    "[id0_trusty_n/1]": "Trusty TEE (Trusted Execution Environment) normal world thread for secure operations",
    "[id0_trusty_n/2]": "Trusty TEE (Trusted Execution Environment) normal world thread for secure operations",
    "[id0_trusty_n/3]": "Trusty TEE (Trusted Execution Environment) normal world thread for secure operations",
    "[id0_trusty_n/4]": "Trusty TEE (Trusted Execution Environment) normal world thread for secure operations",
    "[id0_trusty_n/5]": "Trusty TEE (Trusted Execution Environment) normal world thread for secure operations",
    "[id0_trusty_n/6]": "Trusty TEE (Trusted Execution Environment) normal world thread for secure operations",
    "[id0_trusty_n/7]": "Trusty TEE (Trusted Execution Environment) normal world thread for secure operations",
     "[id0_trusty_k/0]": "Trusty TEE kernel world thread handling secure operations",
    "[id0_trusty_k/1]": "Trusty TEE kernel world thread handling secure operations",
    "[id0_trusty_k/2]": "Trusty TEE kernel world thread handling secure operations",
    "com.google.android.apps.subscriptions.red": "Manages Google Play subscriptions for apps and services",
     "[id0_trusty_c/0]": "Trusty TEE client world thread handling secure client operations",
     "[kworker/R-tmem_]": "Kernel worker thread for Trusted Memory (tmem) management tasks",
     "[kworker/R-task_]": "Kernel worker thread for general task execution in the real-time (R) context",
      "[jbd2/mmcblk0p17-8]": "Journaling block device thread for managing ext4 filesystem journaling on the specified MMC partition",
    "[jbd2/mmcblk0p18-8]": "Journaling block device thread for managing ext4 filesystem journaling on the specified MMC partition",
    "[jbd2/mmcblk0p14-8]": "Journaling block device thread for managing ext4 filesystem journaling on the specified MMC partition",
    "[jbd2/mmcblk0p13-8]": "Journaling block device thread for managing ext4 filesystem journaling on the specified MMC partition",
    "[jbd2/mmcblk0p56-8]": "Journaling block device thread for managing ext4 filesystem journaling on the specified MMC partition",
    "[jbd2/mmcblk0p15-8]": "Journaling block device thread for managing ext4 filesystem journaling on the specified MMC partition",
    "[jbd2/mmcblk0p11-8]": "Journaling block device thread for managing ext4 filesystem journaling on the specified MMC partition",
     "[ipi_cpu_dvfs_rtask]": "Inter-Processor Interrupt task for CPU DVFS (Dynamic Voltage and Frequency Scaling) management, adjusting CPU performance and power consumption",
      "[Init_1_Stress]": "Stress test process spawned by the init system to check system stability during startup or heavy load",
       "[kworker/R-fs16x]": "Kernel worker thread for filesystem operations, handling background tasks related to the FS16x subsystem",
        "[irq/295-ccu]": "Interrupt handler for Camera Control Unit (CCU), managing hardware interrupts from the camera subsystem",
"ps": "Displays currently running processes and their information; used to inspect process status",
"[ccu-enque]": "Kernel thread responsible for queuing tasks to the Camera Control Unit (CCU) for processing",
"teei_daemon": "Daemon process for TEEI (Trusted Execution Environment Interface), handling secure operations and communications",
 "[kworker/R-Secur]": "Kernel worker thread handling security-related background tasks",
  "aee_aed": "Automatic Exception Engine (AED) daemon for handling system crashes and collecting crash reports",
    "aee_aed64": "64-bit version of AED daemon for handling system crashes",
    "aee_aedv": "Variant of AED daemon for verbose crash logging",
    "aee_aedv64": "64-bit variant of AED daemon for verbose crash logging",
      "hypsys_system": "Hypervisor system service managing low-level hardware virtualization and system resources",
  "[kworker/R-mtk-v]": "Kernel worker thread for MediaTek-specific tasks, handling background processing related to MTK hardware components",
  "hypsys_vendor": "Handles vendor-specific Hypervisor/HyperSystem functions, usually related to proprietary hardware drivers and optimizations",
    "hypsys_other": "Covers miscellaneous Hypervisor/HyperSystem tasks not categorized under system or vendor",
    "wmt_launcher": "Responsible for launching and managing WMT (Wireless Module/MediaTek) related services and applications",
    "android.system.suspend-service": "Handles system suspend and resume operations, managing power states and sleep modes for the Android OS",
     "keystore2": "Manages cryptographic keys and secure storage for apps, providing encryption, decryption, and authentication services",
       "android.hardware.keymaster@4.1-service.beanpod": "Provides hardware-backed key management and cryptographic operations for secure app authentication and encryption",
       "[touch_boost]": "Manages touch input performance by temporarily boosting CPU/GPU frequencies during touch interactions to improve responsiveness",
        "[pause_drain_rqs]": "Handles pausing and draining of run queues in the CPU scheduler to manage task execution efficiently",
         "[kfps]": "Kernel thread managing the Frame Per Second (FPS) subsystem, ensuring smooth graphics and display updates",
         "[irq/43-wifi_ant_check]": "Handles Wi-Fi antenna hardware interrupts for checking and managing Wi-Fi antenna status",
          "[f2fs_ckpt-254:61]": "F2FS filesystem checkpoint process, responsible for maintaining filesystem consistency and recovery points",
            "[f2fs_discard-254:61]": "F2FS filesystem discard process, responsible for freeing unused blocks and maintaining storage efficiency",
               "[f2fs_gc-254:61]": "F2FS garbage collection process, responsible for cleaning up and consolidating filesystem blocks to maintain performance",
    "tombstoned": "Android crash handler process that collects and logs crash reports (tombstones) for apps and system processes",
      "[mtk_stp_psm]": "MediaTek STP Power-Saving Manager thread handling low-power management for Bluetooth and connectivity modules",
    "[mtk_stp_uart]": "MediaTek STP UART handler managing Bluetooth and combo-chip UART communication",
    "[mtk_stp_wmt]": "MediaTek Wireless Management Thread coordinating Bluetooth/WiFi/FM serial transport operations",
    "[mtk_stp_btm]": "MediaTek Bluetooth Transport Manager handling Bluetooth firmware communication",
    "[mtk_stp_fw]": "MediaTek STP Firmware handler managing combo-chip firmware operations",
      "[kworker/0:3-events]": "Kernel worker thread handling asynchronous event queue tasks for CPU core 0",
    "[kworker/0:1-events]": "Kernel worker handling event notifications on CPU core 0",
    "[kworker/1:2-events]": "Kernel worker handling event notifications on CPU core 1",
    "[kworker/2:3-events]": "Kernel worker handling event notifications on CPU core 2",
    "[kworker/3:0-events]": "Kernel worker handling event notifications on CPU core 3",
    "[kworker/u8:-events]": "Unbound kernel worker thread for event-related tasks across multiple CPUs",
 "[mtk_wmtd]": "MediaTek WMT daemon managing wireless modules such as Wi-Fi, Bluetooth, GPS, and FM radio",
    "[mtk_stp_psm]": "MediaTek STP (Serial Transport Protocol) power-saving manager controlling power states of wireless modules",
    "[mtk_stp_btif]": "MediaTek Bluetooth interface handler managing low-level BT communication",
    "[mtk_stp_uart]": "MediaTek UART handler for WMT connectivity modules",
    "[mtk_bt_rfkill]": "Controls Bluetooth radio enable/disable state for power management",
    "[mtk_wmt_detect]": "Detects and initializes connected MediaTek wireless hardware components",
    "[mtk_wmt_ctrl]": "Controls WMT modules including Wi-Fi, Bluetooth, FM, and GPS",
    "[mtk_conn_md]": "Manages connectivity modem tasks used by WMT subsystems",
    "[mtk_fm_service]": "Handles MediaTek FM radio hardware and background tasks",
        "statsd": "Android system daemon that collects performance, usage, battery, and event statistics for system analytics, monitoring, and optimization",
      "mtk_wmtd_worker": "Worker thread for the MediaTek WMT daemon, handling background wireless module tasks such as powering on/off and data exchange",
    "mtk_wmtd_service": "Service-level thread used by MediaTek WMT system to coordinate wireless hardware functionality",
    "mtk_wmtd_task": "Background task handling wireless chipset-related operations managed by the WMT subsystem",
    "netd": "Android network daemon responsible for network management including routing, DNS, firewall rules, tethering, and interface configuration",
    "mtk_wmtd_cpu": "CPU worker thread assisting the WMT daemon with hardware operations for wireless modules",
        "zygote64": "Android's 64-bit Zygote process responsible for launching apps by preloading system libraries and forking new app processes to improve startup speed",
            "zygote": "Android's 32-bit Zygote process responsible for launching 32-bit apps by preloading system libraries and forking new app processes to improve startup speed",
             "android.hidl.allocator@1.0-service": "HIDL allocator service that provides shared memory allocation used by hardware HAL components for interprocess communication",
    "android.hidl.allocator@1.0-service.system": "System-level allocator service providing shared memory regions for hardware services",
    "android.hidl.allocator@1.0-service.vendor": "Vendor-specific allocator service that allocates shared memory buffers for vendor HAL implementations",
    "android.hidl.allocator@1.0-service.multiclient": "Allocator service variant that supports multiple HAL clients requiring shared memory allocations",
    "android.hidl.allocator@1.0-service.default": "Default HIDL allocator service instance handling shared memory allocation for HAL frameworks",
     "android.hardware.audio.service-aidl.mediatek":
        "MediaTek AIDL-based audio HAL service responsible for managing audio hardware, routing, playback, recording, volume control, and DSP communication",
    "android.hardware.audio.service.mediatek":
        "MediaTek audio hardware abstraction service managing device audio paths, drivers, and audio effects",
    "android.hardware.audio.effect.service-aidl.mediatek":
        "MediaTek audio effects HAL service handling EQ, bass boost, virtualizer, and sound processing",
    "android.hardware.audio@7.0-service.mediatek":
        "Legacy HIDL MediaTek audio service managing low-level audio device hardware",
    "android.hardware.soundtrigger.service.mediatek":
        "MediaTek sound trigger HAL service handling voice activation, hotword detection, and DSP wake features",
         "android.hardware.bluetooth-service-mediatek":
        "MediaTek Bluetooth HAL service responsible for managing Bluetooth hardware, pairing, audio profiles, LE features, and communication with MTK BT chipset drivers",
    "android.hardware.bluetooth@1.0-service-mediatek":
        "Legacy HIDL MediaTek Bluetooth HAL providing low-level Bluetooth control, radio initialization, and device state management",
    "android.hardware.bluetooth.le-service-mediatek":
        "MediaTek Bluetooth Low Energy service handling BLE advertising, scanning, GATT profiles, and low-power BT operations",
    "mtk_bt_service":
        "MediaTek background BT management process controlling vendor-specific BT extensions, logs, and chipset configuration",
         "android.hardware.health-service.example":
        "Android Health HAL service that monitors device health information such as battery status, charge levels, temperature, and power usage. Provides standardized data to the system and apps for battery management and power optimization.",
    "mtkbt_loader":
        "Bluetooth firmware loader that initializes MediaTek BT chipset during boot, including firmware upload and calibration settings",
        "android.hardware.drm-service.clearkey":
        "Clearkey DRM service providing decryption and license handling for ClearKey-protected media content. It interacts with media frameworks to securely decode encrypted audio/video streams.",
    "android.hardware.drm@1.0-service":
        "Generic DRM HAL service that manages various DRM schemes, including license acquisition, key management, and decryption pipelines.",
    "android.hardware.drm-service.widevine":
        "Widevine DRM service handling secure playback of Google-protected content, including license retrieval and decryption.",
    "android.hardware.drm-service.playready":
        "PlayReady DRM service for handling Microsoft DRM-protected media content.",
    "android.hardware.drm@1.2-service":
        "Updated DRM HAL supporting newer API versions and additional cryptographic algorithms for secure content handling.",
    "android.hardware.gatekeeper-service.beanpod":
        "Gatekeeper HAL service that handles secure user authentication on Android devices, such as PIN, password, or biometric verification. It securely verifies credentials and communicates with the Trusty/TEE for security.",
    "android.hardware.gatekeeper@1.0-service":
        "Generic gatekeeper service managing authentication and secure credential verification for Android devices.",
    "android.hardware.gatekeeper-service":
        "Service providing access control for device authentication, interacting with the hardware-backed Trusted Execution Environment (TEE).",
          "android.hardware.gnss-service.mediatek":
        "GNSS (Global Navigation Satellite System) HAL service for Mediatek devices. Provides location, navigation, and timing information to Android system and apps, interfacing with GNSS hardware.",
    "android.hardware.gnss@1.0-service":
        "Generic GNSS HAL service for Android, responsible for providing GPS and satellite-based location services.",
         "android.hardware.media.c2-mediatek":
        "Android Media Codec2 (C2) HAL service by MediaTek. Handles hardware-accelerated encoding and decoding of audio and video streams, providing efficient multimedia processing for apps like Video Player, Camera, and streaming services.",
    "android.hardware.gnss-service":
        "Service that manages GNSS hardware, providing location updates, satellite info, and navigation data to system and apps.",
        "android.hardware.graphics.allocator-V2-service-mediatek":
        "Graphics memory allocator HAL service (V2) for Mediatek devices. Manages allocation of GPU buffers and graphics memory for apps and system processes, optimizing rendering performance.",
"fidoca": "FIDO authentication daemon — secure login, biometric cryptography, and hardware-bound credentials ko handle karta hai.",
    "vendor.xiaomi.hardware.micharge-service": "Xiaomi fast-charging, thermal protection, charging optimization aur power-delivery controls ko manage karta hai.",
    "mlipayd@1.1": "MediaTek MliPay daemon — secure mobile payment operations aur trusted execution environment interactions.",
    "tidad@1.2": "MediaTek TID authentication daemon — secure identity, TEE communication aur device authentication tasks karta hai.",
    "vsimd": "Vector SIMD daemon — CPU vector instruction optimization, performance tuning, aur low-level hardware math operations.",
    "android.hardware.vibrator-service.mediatek": "Vibration hardware ko control karta hai — haptics, motor patterns, response timing.",
    "android.hardware.cas-service.example": "Conditional Access System example service — encrypted media streams ke liye access control modules.",
    "android.hardware.drm-service.widevine": "Google Widevine DRM service — Netflix/YouTube jaise protected video playback security ko enforce karta hai.",
    "audioserver": "Audio routing, decoding, playback, microphone capture, sound effects aur all audio HAL communication.",
    "credstore": "Credential storage daemon — secure keys, certificates, encrypted data ke liye system ke auth store ko manage karta hai.",
    "gpuservice": "GPU resource manager — rendering, GPU scheduling, hardware acceleration aur graphics memory control.",
    "android.hardware.audio.parameter_parser.service": "Audio hardware ke parameters parse karta hai — mixer paths, device configs, codecs.",
    "surfaceflinger": "Core display compositor — UI frames ko render karta hai, layers merge karta hai aur screen par show karta hai.",
    "[kworker/R-kdmfl]": "Kernel worker thread handling MediaTek DM/Fast Logging tasks (debug + low-level events).",
    "mi_thermald": "Xiaomi thermal daemon controlling CPU/GPU/Battery temperature throttling.",
    "drmserver32": "32-bit DRM media server handling digital rights management for apps and video playback.",
    "[kworker/R-rx0_w]": "Kernel worker handling hardware receive queues (network/subsystem RX0).",
    "[kworker/R-rx1_w]": "Hardware RX1 queue worker.",
    "[kworker/R-rx2_w]": "Hardware RX2 queue worker.",
    "[kworker/R-rx3_w]": "Hardware RX3 queue worker.",
    "[kworker/R-rx4_w]": "Hardware RX4 queue worker.",
    "[kworker/R-rx5_w]": "Hardware RX5 queue worker.",
    "[kworker/R-rx6_w]": "Hardware RX6 queue worker.",
    "[kworker/R-rx7_w]": "Hardware RX7 queue worker.",
    "[kworker/R-rx8_w]": "Hardware RX8 queue worker.",
    "[kworker/R-rx9_w]": "Hardware RX9 queue worker.",
    "[kworker/R-rx10_]": "Hardware RX10 queue worker.",
    "[kworker/R-rx11_]": "Hardware RX11 queue worker.",
    "[kworker/R-rx12_]": "Hardware RX12 queue worker.",
    "[kworker/R-rx13_]": "Hardware RX13 queue worker.",
    "[kworker/R-rx14_]": "Hardware RX14 queue worker.",
    "[kworker/R-rx15_]": "Hardware RX15 queue worker.",
    "traced_probes": "System tracing events collector used by Perfetto and debugging tools.",
    "traced": "Perfetto tracing daemon that records system activity for debugging/profiling.",
    "[kworker/R-md_tx]": "MediaTek modem transmit worker (AP → Modem).",
    "[kworker/R-md_rx]": "MediaTek modem receive worker (Modem → AP).",
    "[cldma_rxq0]": "MediaTek CLDMA modem receive queue thread.",
    "connsyslogger": "MediaTek connectivity subsystem logger (WiFi/Bluetooth/GPS logs).",
    "vtservice": "Video telephony service (IMS/VoLTE video calls).",
    "[kworker/R-fm_ti]": "FM Radio timing/interrupt worker.",
    "[kworker/R-fm_ei]": "FM Radio event/IO worker.",
    "[wlan_rst_thread]": "Wi-Fi driver reset handler.",
    "wlan_assistant": "Wi-Fi assistant responsible for signal optimization and auto-recovery.",
    "mnld": "MediaTek navigation daemon — GPS, A-GPS, GLONASS positioning.",
    "cameraserver": "Camera access manager for apps and HAL.",
    "incidentd": "Android incident report collector (system diagnostics).",
    "installd": "Package installer backend (apk install, update, optimize).",
    "media.extractor": "Audio/video extractor for decoding media streams.",
    "media.metrics": "Media performance statistics collector.",
    "storaged": "Storage stats manager — IO counters, disk health.",
    "wificond": "Wi-Fi hardware control daemon (scanning, AP mode).",
    "emdlogger": "MediaTek modem diagnostic log service.",
    "lbs_dbg_ext": "Location-Based Service debugger.",
    "misight": "MiSight system intelligence crash analyzer.",
    "fdpp": "File descriptor policy protector (security).",
    "shelld": "System shell server (adb shell backend).",
    "thermald": "Thermal management daemon.",
    "mediaserver": "Legacy media framework service.",
    "miuibooster": "Xiaomi performance booster for UI smoothness.",
    "mobile_log_d": "Mobile network logging daemon.",
    "netdiag": "Network diagnostics service.",
    "camerahalserver": "MediaTek camera HAL server.",
    "mtk_agpsd": "MediaTek A-GPS daemon.",
    "v3avpud": "MediaTek video accelerator (AVPU).",
    "vendor.mediatek.hardware.pq_aidl-service": "Mediatek picture quality engine service.",
    "[kworker/R-kbase]": "ARM Mali GPU kernel job scheduler worker.",
    "media.swcodec": "Software media codecs backend.",
    "gatekeeperd": "Gatekeeper authentication (PIN/password hashing).",
    "update_engine": "System updater/OTA engine.",
    "jxnosfastswitch": "Xiaomi fast app switching service.",
    "android.hardware.biometrics.fingerprint@2.1-service": "Fingerprint HAL service.",
    "netdagent": "Network data agent for firewall and routing.",
    "vendor.microtrust.hardware.thh@2.0-service": "TEE security handler from Microtrust.",
    "vendor.silead.hardware.fingerprintext@1.0-service": "Silead fingerprint extension HAL.",
    "vendor.xiaomi.sensor.citsensorservice@2.0-service": "Xiaomi calibration & test sensors service.",
    "system_server": "Main Android system process running all core services.",
    "millet_monitor": "Xiaomi Millet system monitoring daemon.",
    "android.hardware.wifi-service-lazy": "Lazy-loaded Wi-Fi HAL service.",
    "[main_thread]": "Main hardware driver thread.",
    "[hif_thread]": "High-speed interface thread.",
    "[rx_thread]": "Hardware receive thread.",
    "com.miui.miwallpaper": "Mi Wallpaper engine.",
    "com.android.networkstack.process": "Android Network Stack service.",
    "com.mediatek.ims": "IMS service (VoLTE/VoWiFi).",
    "com.miui.cotaservice": "Carrier provisioning service.",
    "com.android.se": "Secure element service.",
    "com.android.phone": "Telephony service.",
    "com.android.systemui": "Android system UI (status bar, notifications).",
    "com.miui.home": "MIUI Launcher.",
    "com.xiaomi.bluetooth": "Xiaomi Bluetooth extension services.",
    "com.android.bluetooth": "Android Bluetooth stack.",
    "com.google.android.ext.services": "Google extension services.",
    "charge_logger": "Charging events logger.",
    "mcd": "MediaTek connectivity daemon.",
    "lc_wifi_sar_server": "SAR (radiation) control for Wi-Fi power.",
    "MI_RIC": "Xiaomi security integrity control.",
    "mtd@1.3": "MediaTek trusted daemon.",
    "com.google.android.providers.media.module": "Google media provider service.",
    "com.miui.daemon": "Xiaomi system daemon.",
    "com.xiaomi.touchservice": "Touch response & haptics tuner.",
    "system": "Android system user process.",
    "org.ifaa.aidl.manager": "IFAA biometric authentication manager.",
    "com.xiaomi.xmsfkeeper": "Xiaomi push notification keeper.",
    "com.tencent.soter.soterserver": "WeChat Soter security service.",
    "com.mediatek.voicecommand": "Voice command service.",
    "com.xiaomi.xmsf": "Xiaomi messaging/push framework.",
    "com.google.android.inputmethod.latin": "Gboard keyboard.",
    "com.miui.securitycenter.remote": "MIUI security center remote service.",
    "com.miui.weather2": "Mi Weather app.",
    "com.instagram.android": "Instagram app.",
    "com.facebook.katana": "Facebook app.",
    "com.android.vending": "Google Play Store.",
    "com.miui.powerkeeper": "Xiaomi power management (battery saver).",
    "com.lbe.security.miui": "MIUI privacy + permission manager.",
    "com.google.android.apps.messaging:rcs": "RCS messaging module.",
    "com.miui.misound": "Xiaomi audio enhancement engine.",
    "com.miui.msa.global": "MIUI system ads core service.",
    "com.google.android.as": "Android adaptive services.",
    "com.facebook.orca": "Messenger app.",
    "com.miui.videoplayer": "Mi Video player.",
    "com.miui.gallery": "Xiaomi gallery app.",
    "com.android.thememanager": "Theme Manager.",
    "com.google.android.apps.photos": "Google Photos.",
    "com.miui.mediaeditor": "Mi Gallery editor.",
    "com.google.android.adservices.api": "Google Ads API.",
    "com.google.android.apps.messaging": "Google Messages.",
    "com.android.chrome": "Chrome browser.",
    "com.google.android.googlequicksearchbox:googleapp": "Google App main process.",
    "android.process.acore": "Contacts + system core DB engine.",
     "org.ifaa.aidl.manager": "Handles biometric authentication (IFAA standard) used for fingerprint/face ID.",
    "com.xiaomi.xmsfkeeper": "Xiaomi push messaging service keeper.",
    "com.tencent.soter.soterserver": "Tencent Soter security framework for secure authentication.",
    "com.mediatek.voicecommand": "MediaTek voice command handling service.",
    "[kworker/7:2-events]": "Kernel worker handling hardware/software asynchronous events.",
    "[kworker/4:10H-kverityd]": "Kernel worker for Android's file integrity verification (verity).",
    "[kworker/3:1-pm]": "Kernel worker handling power management events.",
    "com.xiaomi.xmsf": "Xiaomi push framework service (for notifications).",
    "com.google.android.inputmethod.latin": "Gboard keyboard input service.",
    "[kworker/3:0-events]": "Kernel worker handling system events.",
    "[kworker/3:3-mm_percpu_wq]": "Kernel memory management worker thread (per-CPU).",
    "com.miui.securitycenter.remote": "Remote security service for MIUI security center.",
    "com.miui.weather2": "MIUI Weather application background process.",
    "com.instagram.android": "Instagram main app process.",
    "com.facebook.katana": "Facebook main app process.",
    "com.android.vending": "Google Play Store app process.",
    "[kworker/R-kbase]": "Kernel worker related to GPU (Mali) base driver tasks.",
    "[kworker/u16:1-adb]": "Kernel worker handling ADB (Android Debug Bridge) events.",
    "com.miui.powerkeeper": "MIUI battery and power optimization system.",
    "com.lbe.security.miui": "MIUI security service (permissions, privacy).",
    "[kworker/2:2-events]": "Kernel worker handling hardware events.",
    "ps": "System command for listing running processes.",
    "[cat]": "System command to read/display files.",
    "com.milink.service:audio": "MiLink wireless streaming audio service.",
    "com.miui.analytics": "Xiaomi analytics/tracking service.",
    "com.xiaomi.aicr:cognitionService": "Xiaomi AI cognition service.",
    "com.android.camera": "Android camera main app process.",
    "com.google.android.apps.messaging:rcs": "Google Messages RCS service.",
    "com.miui.misound": "Xiaomi MiSound audio enhancement service.",
    "com.miui.msa.global": "MSA global ad + system services.",
    "com.google.android.as": "Android System intelligence / adaptive services.",
    "com.facebook.orca": "Facebook Messenger main process.",
    "[kworker/u17:1-ged_notify_sw_vsync]": "GPU event daemon worker for vsync notifications.",
    "com.miui.videoplayer": "MIUI Video Player background service.",
    "com.miui.gallery": "MIUI Gallery background tasks.",
    "com.android.thememanager": "Theme manager process.",
    "com.google.android.apps.photos": "Google Photos background service.",
    "com.miui.mediaeditor": "MIUI media editor processing service.",
    "com.google.android.adservices.api": "Google ad services API process.",
    "com.google.android.apps.messaging": "Google Messages main process.",
    "com.android.chrome": "Chrome browser main app process.",
    "com.google.android.googlequicksearchbox:googleapp": "Google app main service (search, assistant).",
    "com.google.android.webview:sandboxed_process0": "Sandboxed WebView content rendering process.",
    "android.process.acore": "Core Android process (contacts, accounts, sync).",
    "com.miui.securitycore:provider": "MIUI security core provider.",
    "NativeHangService": "Service monitoring native process hangs.",
    "com.android.chrome_zygote": "Chrome zygote process (preload for performance).",
    "com.android.chrome:sandboxed_process0:0": "Chrome sandboxed renderer process 0.",
    "com.google.android.tts": "Google Text-to-Speech engine service.",
    "com.facebook.services": "Background Facebook service framework.",
    "com.android.chrome:sandboxed_process0:1": "Chrome sandboxed renderer process 1.",
    "com.snapchat.android": "Snapchat main app process.",
    "com.android.chrome:sandboxed_process0:2": "Chrome sandboxed renderer process 2.",
    "com.xiaomi.mipicks": "Mi Picks (Xiaomi app recommendation system).",
    "com.android.chrome:privileged_process2": "Chrome privileged web rendering process.",
    "android.process.media": "System media scanner + media storage process.",
    "[kworker/2:4H-kverityd]": "Kernel worker verifying file system integrity (verity).",
    "com.miui.msa.global:ui": "MSA user interface process.",
    "com.miui.securitycore:provider": "MIUI security content provider.",
    "[kworker/2:0-events]": "Kernel worker thread handling events on CPU 2",
    "[kworker/R-kbase]": "Generic kernel worker thread for background tasks",
    "[kworker/1:2-events_freezable_power_]": "CPU 1 worker handling freezable power events",
    "com.xiaomi.bluetooth": "Xiaomi Bluetooth service handling device connections",
    "com.android.bluetooth": "Android system Bluetooth service managing connections and devices",
    "com.google.android.ext.services": "Google Play Services extended functionalities",
    "charge_logger": "Logs device charging events and battery statistics",
    "mcd": "Modem Communication Daemon handling mobile network communication",
    "lc_wifi_sar_server": "Manages Wi-Fi SAR (Specific Absorption Rate) for antennas",
    "MI_RIC": "Xiaomi Radio Interface Controller, manages cellular radio events",
    "mtd@1.3": "Memory Technology Device service, manages flash memory access",
    "com.google.android.providers.media.module": "Media provider module for storage and media files",
    "com.miui.daemon": "MIUI system daemon handling background tasks",
    "com.xiaomi.touchservice": "Handles Xiaomi touchscreen events and gestures",
    "system": "Core Android system process",
    "org.ifaa.aidl.manager": "Biometric and security authentication manager",
    "com.xiaomi.xmsfkeeper": "Maintains Xiaomi background services",
    "com.tencent.soter.soterserver": "Tencent security authentication server for SOTER framework",
    "com.mediatek.voicecommand": "Mediatek voice command service",
    "[kworker/7:7H-kverityd]": "Kernel worker for dm-verity file integrity verification on CPU 7",
    "[kworker/7:0-events]": "Kernel worker thread handling events on CPU 7",
    "[kworker/1:3-events_freezable_power_]": "CPU 1 worker handling freezable power events",
    "com.xiaomi.xmsf": "Xiaomi system framework service",
    "com.google.android.inputmethod.latin": "Google Latin IME (keyboard) service",
    "[kworker/3:2H-kverityd]": "Kernel dm-verity verification worker on CPU 3",
    "[kworker/0:2-events_freezable_power_]": "CPU 0 worker handling freezable power events",
    "com.miui.securitycenter.remote": "MIUI Security Center remote management service",
    "com.miui.powerkeeper": "MIUI PowerKeeper service to optimize battery usage",
    "com.lbe.security.miui": "MIUI security service for app permissions and protection",
    "[kworker/1:0-mm_percpu_wq]": "Memory management worker thread on CPU 1",
    "com.xiaomi.glgm": "Xiaomi gesture and logic manager service",
    "[kworker/6:2-events]": "Kernel worker handling events on CPU 6",
    "[kworker/0:1H-kblockd]": "Kernel block device worker on CPU 0",
    "[kworker/6:3H-kverityd]": "Kernel dm-verity worker on CPU 6",
    "[kworker/6:6H-kblockd]": "Kernel block device worker on CPU 6",
    "[kworker/2:2H-kblockd]": "Kernel block worker thread CPU 2",
    "[kworker/5:1H-kverityd]": "Kernel dm-verity worker CPU 5",
    "[kworker/1:2H-kverityd]": "Kernel dm-verity worker CPU 1",
    "[kworker/3:3H-kverityd]": "Kernel dm-verity worker CPU 3",
    "[kworker/4:0H-kblockd]": "Kernel block worker CPU 4",
    "[kworker/4:0-mm_percpu_wq]": "Memory management worker CPU 4",
    "[kworker/u17:2-rx5_worker]": "Device driver worker thread handling RX5 queue",
    "[kworker/u16:0-adb]": "Kernel worker handling ADB (Android Debug Bridge) tasks",
    "[kworker/2:1-events]": "Kernel event worker CPU 2",
    "[kworker/5:3H-kverityd]": "Kernel dm-verity worker CPU 5",
    "[kworker/0:1-events_freezable_power_]": "CPU 0 worker handling freezable power events",
    "[kworker/6:0H-kverityd]": "Kernel dm-verity worker CPU 6",
    "[kworker/2:3H-kblockd]": "Kernel block worker CPU 2",
    "[kworker/1:4-events_freezable_power_]": "CPU 1 worker handling freezable power events",
    "[kworker/1:0H-kverityd]": "Kernel dm-verity worker CPU 1",
    "[kworker/7:1H-kverityd]": "Kernel dm-verity worker CPU 7",
    "[kworker/7:2H-kverityd]": "Kernel dm-verity worker CPU 7",
    "[kworker/6:1H-kblockd]": "Kernel block worker CPU 6",
    "[kworker/3:2-events]": "Kernel event worker CPU 3",
    "[kworker/3:3]": "Generic kernel worker CPU 3",
    "[kworker/6:1-events]": "Kernel event worker CPU 6",
    "[kworker/6:3]": "Generic kernel worker CPU 6",
    "[kworker/0:0-events]": "Kernel event worker CPU 0",
    "[kworker/5:0-events]": "Kernel event worker CPU 5",
    "com.snapchat.android": "Snapchat Android app process",
    "[kworker/5:0H-kblockd]": "Kernel block worker CPU 5",
    "[kworker/3:0H-kverityd]": "Kernel dm-verity worker CPU 3",
    "[kworker/3:1H-kverityd]": "Kernel dm-verity worker CPU 3",
    "[kworker/4:1H-kblockd]": "Kernel block worker CPU 4",
    "[kworker/1:1H-kverityd]": "Kernel dm-verity worker CPU 1",
    "[kworker/5:1]": "Generic kernel worker CPU 5",
    "[kworker/3:4H-kverityd]": "Kernel dm-verity worker CPU 3",
    "[kworker/3:5H-kverityd]": "Kernel dm-verity worker CPU 3",
    "[kworker/1:3H-kblockd]": "Kernel block worker CPU 1",
    "[kworker/7:3H]": "Generic kernel worker CPU 7",
    "[kworker/7:4H-kblockd]": "Kernel block worker CPU 7",
    "[kworker/4:1-events]": "Kernel event worker CPU 4",
    "[kworker/4:2]": "Generic kernel worker CPU 4",
    "[kworker/4:4H-kverityd]": "Kernel dm-verity worker CPU 4",
    "ps": "Command to list running processes",
    "com.milink.service:audio": "Milink audio service handling multimedia",
    "com.miui.analytics": "MIUI analytics service collecting usage data",
    "com.xiaomi.aicr:cognitionService": "Xiaomi AI cognition service",
    "com.android.camera": "Android camera service",
    "com.google.android.apps.messaging:rcs": "Google messaging app with RCS support",
    "com.miui.misound": "MIUI audio enhancement service",
    "com.miui.msa.global": "MIUI global service for app recommendations",
    "com.google.android.as": "Google Assistant service",
    "com.android.thememanager": "Android theme manager service",
     "[kworker/7:0-mm_percpu_wq]": "Memory management worker thread on CPU 7",
    "[kworker/1:3-events_freezable_power_]": "CPU 1 worker handling freezable power events",
    "com.xiaomi.xmsf": "Xiaomi system framework service",
    "com.google.android.inputmethod.latin": "Google Latin IME (keyboard) service",
    "[kworker/3:2H-kverityd]": "Kernel dm-verity file integrity verification worker CPU 3",
    "[kworker/0:2-events_freezable_power_]": "CPU 0 worker handling freezable power events",
    "com.miui.securitycenter.remote": "MIUI Security Center remote management service",
    "com.miui.powerkeeper": "MIUI PowerKeeper service to optimize battery usage",
    "com.lbe.security.miui": "MIUI security service for app permissions and protection",
    "[kworker/1:0-events]": "Kernel event worker CPU 1",
    "com.xiaomi.glgm": "Xiaomi gesture and logic manager service",
    "[kworker/6:2-events]": "Kernel event worker CPU 6",
    "[kworker/0:1H-kverityd]": "Kernel dm-verity worker CPU 0",
    "[kworker/u17:2-mali_jd]": "GPU worker thread handling Mali GPU jobs",
    "[kworker/u16:0-adb]": "Kernel worker handling ADB (Android Debug Bridge) tasks",
    "[kworker/2:1-events]": "Kernel event worker CPU 2",
    "[kworker/5:3H-kblockd]": "Kernel block device worker CPU 5",
    "[kworker/2:3H-kblockd]": "Kernel block device worker CPU 2",
    "[kworker/6:1-mm_percpu_wq]": "Memory management worker thread CPU 6",
    "com.snapchat.android": "Snapchat Android app process",
    "[kworker/3:5H-kverityd]": "Kernel dm-verity worker CPU 3",
    "[kworker/7:4H-kblockd]": "Kernel block device worker CPU 7",
    "[kworker/R-kbase]": "Generic kernel worker for background tasks",
    "[kworker/5:2H-kblockd]": "Kernel block worker CPU 5",
    "[kworker/4:2H-kverityd]": "Kernel dm-verity worker CPU 4",
    "[kworker/u17:1-mali_jd]": "GPU worker thread handling Mali GPU jobs",
    "[kworker/0:3H-kblockd]": "Kernel block worker CPU 0",
    "[kworker/u16:2-adb]": "ADB-related worker thread",
    "[kworker/6:5H-kblockd]": "Kernel block worker CPU 6",
    "[kworker/6:7H-fsverity_read_queue]": "Kernel worker handling fs-verity read queue",
    "[kworker/1:1-events_freezable_power_]": "CPU 1 worker handling freezable power events",
    "com.milink.service:audio": "Milink audio service handling multimedia",
    "com.miui.analytics": "MIUI analytics service collecting usage data",
    "com.xiaomi.aicr:cognitionService": "Xiaomi AI cognition service",
    "com.android.camera": "Android camera service",
    "com.google.android.apps.messaging:rcs": "Google messaging app with RCS support",
    "com.miui.misound": "MIUI audio enhancement service",
    "com.miui.msa.global": "MIUI global service for app recommendations",
    "com.google.android.as": "Google Assistant service",
    "[kworker/2:2-events]": "Kernel event worker CPU 2",
    "[kworker/0:3-events]": "Kernel event worker CPU 0",
    "[kworker/3:3-events]": "Kernel event worker CPU 3",
    "[kworker/2:0H-kblockd]": "Kernel block worker CPU 2",
    "[kworker/5:0-events]": "Kernel event worker CPU 5",
    "[kworker/0:1-events_power_efficient]": "CPU 0 worker for power-efficient events",
    "com.google.android.apps.safetyhub": "Google Safety Hub service for safety features",
    "[kworker/4:1H-kverityd]": "Kernel dm-verity worker CPU 4",
    "[kworker/7:1H]": "Generic kernel worker CPU 7",
    "com.android.thememanager": "Android theme manager service",
    "[kworker/4:1-events]": "Kernel event worker CPU 4",
    "com.google.android.adservices.api": "Google Ad Services API service",
    "[kworker/1:4-events_freezable_power_]": "CPU 1 worker handling freezable power events",
    "com.google.android.apps.messaging": "Google Messages app process",
    "com.google.android.googlequicksearchbox:googleapp": "Google app search process",
    "[kworker/1:3H-fsverity_read_queue]": "Kernel worker reading fs-verity queue",
    "[kworker/1:4H-kblockd]": "Kernel block worker CPU 1",
    "[kworker/u17:0-mali_jd]": "GPU worker thread handling Mali GPU jobs",
    "com.miui.securitycore:provider": "MIUI security core service provider",
    "NativeHangService": "Service monitoring app or system hangs",
    "com.miui.android.fashiongallery": "MIUI fashion gallery app service",
    "com.google.android.googlequicksearchbox:search": "Google search process",
    "com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:": "WebView sandboxed renderer process",
    "com.facebook.services": "Facebook background services",
    "[kworker/0:0H]": "Generic kernel worker CPU 0",
    "[kworker/0:0]": "Generic kernel worker CPU 0",
    "[kworker/2:0-mm_percpu_wq]": "Memory management worker thread on CPU 2",
    "[kworker/2:3]": "Generic kernel worker CPU 2",
    "android.process.media": "Android media service managing media files",
    "com.bykea.pk": "Bykea app service",
    "[kworker/5:1-events]": "Kernel event worker CPU 5",
    "com.xiaomi.discover": "Xiaomi Discover service for app recommendations",
    "[kworker/u16:3-cmdq_pkt_destroy_wq]": "Kernel worker for Command Queue packet destruction",
    "com.google.android.gms.persistent": "Persistent Google Play Services process",
    "com.google.android.gms": "Google Play Services core process",
    "bip": "Bearer Independent Protocol service (mobile network related)",
    "volte_imsm_93": "VoLTE IMS management service",
    "gsm0710muxd": "GSM multiplexing daemon for modem communication",
    "volte_stack": "VoLTE protocol stack service",
    "volte_ua": "VoLTE user agent process",
    "volte_imcb": "IMS control block for VoLTE",
    "epdg_wod": "Evolved Packet Data Gateway service",
    "mtkfusionrild": "Mediatek RIL (Radio Interface Layer) fusion service",
    "[kworker/3:0H-kverityd]": "Kernel dm-verity worker CPU 3",
    "com.miui.weather2": "MIUI Weather app service",
    "[kworker/6:0H-kblockd]": "Kernel block device worker CPU 6",
    "[kworker/R-kbase]": "Generic kernel worker handling background tasks",
    "[kworker/6:1H-kblockd]": "Kernel block device worker CPU 6",
    "[kworker/6:2H-fsverity_read_queue]": "Kernel worker reading fs-verity queue CPU 6",
    "[kworker/6:3H-fsverity_read_queue]": "Kernel worker reading fs-verity queue CPU 6",
    "[kworker/6:4H-fsverity_read_queue]": "Kernel worker reading fs-verity queue CPU 6",
    "[kworker/6:6H-fsverity_read_queue]": "Kernel worker reading fs-verity queue CPU 6",
    "com.google.android.gms.unstable": "Unstable Google Play Services process",
    "[kworker/6:8H-kblockd]": "Kernel block device worker CPU 6",
    "[kworker/6:9H-kblockd]": "Kernel block device worker CPU 6",
    "[kworker/3:1H-kblockd]": "Kernel block device worker CPU 3",
    "[kworker/u17:3-composer_wq]": "GPU compositor worker thread on CPU 17",
    "[kworker/4:0H-kblockd]": "Kernel block device worker CPU 4",
    "[kworker/1:2-events_freezable_power_]": "CPU 1 worker handling freezable power events",
    "ps": "Process status listing command/process",
    "com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:": "WebView sandboxed renderer process",
    "com.whatsapp": "WhatsApp messaging app process",
    "[kworker/u16:1-events_unbound]": "Kernel unbound event worker CPU 16",
    "[erofs_worker/1]": "EROFS filesystem worker thread 1",
    "[erofs_worker/2]": "EROFS filesystem worker thread 2",
    "[erofs_worker/3]": "EROFS filesystem worker thread 3",
    "[erofs_worker/4]": "EROFS filesystem worker thread 4",
    "[erofs_worker/5]": "EROFS filesystem worker thread 5",
    "[erofs_worker/6]": "EROFS filesystem worker thread 6",
    "[erofs_worker/7]": "EROFS filesystem worker thread 7",
    "[kworker/3:0-mm_percpu_wq]": "Memory management worker thread CPU 3",
    "com.mi.globalminusscreen": "MIUI Global Minus Screen app/service",
    "webview_zygote": "WebView zygote process for app web rendering",
    "starter": "System starter/init service",
    "charon": "IPSec/IKE daemon for VPN connections",
    "com.linkedin.android": "LinkedIn Android app process",
    "[kworker/R-vdec_]": "Video decode kernel worker thread",
    "[kworker/7:3-events]": "Kernel event worker CPU 7",
    "com.android.settings": "Android settings app",
    "com.android.settings.intelligence": "Android smart settings service",
    "[kworker/5:2-mm_percpu_wq]": "Memory management worker thread CPU 5",
    "com.facebook.katana": "Facebook Android app",
    "com.milink.service": "Milink service handling media/audio",
    "com.android.deskclock": "Android clock app",
    "com.microsoft.skydrive": "Microsoft OneDrive service",
    "com.facebook.appmanager": "Facebook app manager service",
    "com.android.vending": "Google Play Store",
    "com.google.android.permissioncontroller": "Google permission management service",
    "com.google.android.webview:webview_service": "WebView service for app web rendering",
    "com.android.vending:background": "Background tasks of Google Play Store",
    "iptables-restore": "Restores saved firewall rules",
    "ip6tables-restore": "Restores saved IPv6 firewall rules",
    "com.miui.screenrecorder": "MIUI screen recording service",
    "com.android.htmlviewer": "Android HTML viewer process",
    "com.miui.cloudservice": "MIUI Cloud service for syncing data",
    "com.google.android.setupwizard": "Google setup wizard process",
    "[kworker/4:3-mm_percpu_wq]": "Memory management worker thread CPU 4",
    "com.xiaomi.finddevice": "Xiaomi Find Device service",
    "com.xiaomi.simactivate.service": "Xiaomi SIM activation service",
    "com.xiaomi.account": "Xiaomi account management service",
    "com.android.DeviceAsWebcam": "Device webcam service",
    "com.google.android.gms.ui": "Google Play Services UI process",
    "com.xiaomi.mipicks": "Xiaomi Mi Picks app/service",
    "com.google.android.cellbroadcastreceiver": "Android Cell Broadcast receiver",
    "com.google.android.youtube": "YouTube app process",
    "com.wallet.zindigi": "Zindigi wallet app",
    "com.android.chrome": "Google Chrome browser",
    "com.android.chrome:privileged_process0": "Privileged Chrome process for rendering and extensions",
     "[kworker/R-kbase]": "Generic kernel worker handling background tasks",
    "com.android.chrome_zygote": "Chrome zygote process for spawning Chrome renderer processes",
    "com.android.chrome:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0": "Chrome sandboxed renderer process",
    "com.google.android.googlequicksearchbox:interactor": "Google app interactor process for search and assistant features",
    "com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:": "WebView sandboxed renderer process",
    "pk.com.telenor.phoenix": "Telenor Phoenix app process (telecom service app)",
    "com.android.htmlviewer:remote": "Android HTML viewer remote process",
    "com.android.updater": "System update service",
    "com.miui.securitycenter": "MIUI Security Center app for device protection",
    "com.google.android.apps.tachyon": "Google Duo video calling app process",
    "fuelgauged": "Battery fuel gauge daemon — battery percentage, temperature, charge cycle, health stats calculate karta hai.",
    "ccci_mdinit": "MediaTek modem initialization — modem ko boot, configure aur communication link initialize karta hai.",
    "ccci_rpcd": "MediaTek CCCI RPC daemon — AP (Android Processor) aur Modem ke beech RPC communication handle karta hai.",
     "[kworker/u17:4-fbt_cpu]": "Kernel worker thread for FBT (Frame-Based Throttling). Yeh CPU load, frame rendering performance, scheduler tuning aur thermal throttling ko dynamically adjust karta hai — mainly smooth UI frame rate maintain karne ke liye.",
         "[kworker/0:2H-kverityd]": "Kernel worker thread related to kverityd (dm-verity daemon). Yeh system partition aur critical read-only partitions ki integrity verify karta hai, corruption detect karta hai, aur Verified Boot security maintain karta hai.",
    "wfca": "Wi-Fi/Connectivity Agent — WiFi calling, carrier WiFi features aur network optimization tasks perform karta hai.",
    "android.hardware.graphics.allocator@2.0-service":
        "Generic Android graphics allocator HAL service, responsible for allocating and managing GPU buffers for rendering pipelines.",
    "android.hardware.graphics.allocator-service":
        "Older version of graphics memory allocator service, providing GPU buffer allocation and memory management for system and apps.",
         "android.hardware.graphics.composer@3.3-service":
        "Graphics Composer HAL (v3.3) manages the composition of display layers onto the screen. Optimizes rendering by offloading layer composition to hardware, improving performance and reducing CPU/GPU load.",
    "android.hardware.graphics.composer@2.1-service":
        "Earlier version of the Graphics Composer HAL, responsible for composing multiple graphical layers for display output.",
            "[kworker/7:4H-kverityd]": "Kernel worker thread that handles dm-verity background tasks. It verifies system partitions to ensure no tampering or corruption occurs during Android Verified Boot.",
            "[kworker/0:0-mm_percpu_wq]": "Kernel worker handling memory management tasks on per-CPU workqueue (CPU 0).",
            "[kworker/u16:0-events_unbound]": "A kernel worker thread on CPU 16 handling unbound events, which are generic background tasks not tied to a specific CPU or hardware queue.",
            "[kworker/0:0-sock_diag_events]": "Kernel worker thread for handling socket diagnostic events and network socket monitoring (CPU 0).",
            "[kworker/6:5H-kblockd]": "Kernel worker thread on CPU 6, worker ID 5H, dedicated to block device operations (disk I/O tasks) such as reading/writing data, scheduling block device requests, and managing deferred storage-related kernel work.",
            "com.google.android.apps.wellbeing": "Google's Digital Wellbeing app; monitors and reports device usage patterns, screen time, app activity, and helps users manage phone habits to promote healthier digital usage.",
            "adbd": "Android Debug Bridge daemon; a background process that allows communication between an Android device and a computer for debugging, file transfer, app installation, and command execution via ADB.",
}
adb_path = r"E:\ADB\platform-tools\adb.exe"
Countprocesses = 0

def run_adb(cmd):
    try:
        result = subprocess.run([adb_path] + cmd.split(), capture_output=True, text=True)
        if result.returncode == 0:
            return result.stdout.strip()
    except Exception as e:
        print("ADB error:", e)
    return ""

def map_state(stat):
    mapping = {
        "R": "Running",
        "S": "Sleeping",
        "D": "Uninterruptible Sleep",
        "T": "Stopped",
        "Z": "Zombie",
        "I": "Idle",
        "X": "Dead",
    }
    letter = stat[0] if stat else "?"
    return mapping.get(letter, "Unknown")

def purpose(name):
    if name in process_purpose:
        return process_purpose[name]
    else:
        return "N/A"

def get_all_processes():
    output = run_adb("shell ps -e -o USER,PID,PPID,VSZ,RSS,STAT,NAME")
    procs = []
    lines = output.splitlines()

    for line in lines[1:]:
        parts = line.split()
        if len(parts) < 7:
            continue

        procs.append({
            "user": parts[0],
            "pid": parts[1],
            "ppid": parts[2],
            "vsz": int(parts[3]),
            "rss": int(parts[4]),
            "state": map_state(parts[5]),
            "name": parts[6],
        })

    return procs

def get_cpu_threads():
    output = run_adb("shell top -b -n 1 -o PID")
    cpu_threads = {}

    for line in output.splitlines()[1:]:
        parts = line.split()
        if len(parts) < 10:
            continue

        pid = parts[0]

        try:
            cpu = float(parts[8])
        except:
            cpu = 0.0

        try:
            threads = int(parts[4])
        except:
            threads = 0

        cpu_threads[pid] = {
            "cpu": cpu,
            "threads": threads
        }

    return cpu_threads

def get_sched(pid):
    output = run_adb(f"shell cat /proc/{pid}/sched")
    policy = None

    for line in output.splitlines():
        if "policy" in line:
            try:
                policy = int(line.split(":")[1].strip())
            except:
                policy = None

    return policy


def map_scheduler(policy):
    sched_map = {
        0: "CFS (Completely Fair Scheduler) default",
        1: "SCHED_FIFO (Real-time, FIFO)",
        2: "SCHED_RR (Real-time, Round-Robin)",
        3: "SCHED_DEADLINE (Deadline-based, Real-time)"
    }
    return sched_map.get(policy, "Unknown / Adaptive")

def inspect_processes():
    global Countprocesses

    procs = get_all_processes()
    cpu_threads = get_cpu_threads()

    print("=" * 120)
    print("ANDROID PROCESS INSPECTOR — FULL STATE + PURPOSE")
    print("=" * 120)

    all_data = []

    for p in procs:
        pid = p["pid"]
        name = p["name"]

        ct = cpu_threads.get(pid, {})
        cpu = ct.get("cpu", 0.0)
        threads = ct.get("threads", 0)

        policy = get_sched(pid)
        scheduler = map_scheduler(policy)

        info = {
            "pid": pid,
            "name": name,
            "user": p["user"],
            "ppid": p["ppid"],
            "threads": threads,
            "cpu_percent": cpu,
            "rss_kb": p["rss"],
            "vms_kb": p["vsz"],
            "Purpose":purpose(name),
            "state": p["state"],
            "scheduler": scheduler,
        }

        Countprocesses += 1
        all_data.append(info)
    return all_data


# -----------------------------
if __name__ == "__main__":
    data = inspect_processes()
